import React, { useState, useEffect, useRef } from 'react';
import { 
  ShieldCheck, 
  Globe, 
  Send, 
  ArrowRight,
  UserCheck, 
  Sparkles, 
  Clock, 
  ArrowLeft, 
  HeartPulse, 
  FileText, 
  Video, 
  CheckCircle2, 
  AlertTriangle,
  Activity,
  Lock,
  ChevronRight,
  CheckCircle,
  Loader2,
  Mail,
  Menu,
  RotateCcw,
  Star,
  Stethoscope,
  UsersRound
} from 'lucide-react';
import { supabase } from '../../lib/supabaseClient';
import LibertyMDFooterRibbon from './LibertyMDFooterRibbon';
import { PatientOathEmblem } from './LibertyMDFooterBadges';
import LibertyMD3DBlobLogo from './LibertyMD3DBlobLogo';
import LibertyMDMedicalCrossLogo from './LibertyMDMedicalCrossLogo';
import LibertyMDHumanSilhouettes from './LibertyMDHumanSilhouettes';
import LibertyMDPremiumLogo from './LibertyMDPremiumLogo';
import LibertyMDParticleWaveSeparator from './LibertyMDParticleWaveSeparator';
import {
  LibertyMDHealthLibrarySection,
  LibertyMDPatientStoriesSection,
  LibertyMDPhoneCareSection,
  LibertyMDPricingSection,
} from './LibertyMDMarketingSections';
import {
  LibertyMDAccountDrawer,
  LibertyMDDemographicsPrompt,
  LibertyMDReportGate,
  type LibertyMDHistoryItem,
} from './LibertyMDCareControls';

interface LibertyMDAppProps {
  onBack?: () => void;
}

interface ChatMessage {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  options?: string[];
  kind?: 'normal' | 'system' | 'emergency' | 'report';
  triageData?: {
    severity: 'low' | 'moderate' | 'urgent';
    possibleCauses: string[];
    actionPlan: string[];
    redFlags: string[];
  };
}

type ChatPhase =
  | 'initial'
  | 'demographics_required'
  | 'intake'
  | 'report_gate'
  | 'report_ready'
  | 'emergency_end'
  | 'clinical_review_needed'
  | 'error';

interface LibertyMDProfile {
  display_name?: string | null;
  email?: string | null;
  avatar_url?: string | null;
  age?: number | null;
  sex_at_birth?: string | null;
}

interface LibertyReport {
  summary: string;
  differentials: Array<{
    name: string;
    confidence?: string;
    description?: string;
    reason?: string;
  }>;
  plan: string[];
  redFlags: string[];
  soap: {
    subjective: string;
    objective: string;
    assessment: string;
    plan: string;
  };
}

const asText = (value: unknown, fallback = '') => {
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) return value.filter(Boolean).join('\n');
  if (value && typeof value === 'object') return JSON.stringify(value, null, 2);
  return fallback;
};

const listFrom = (value: unknown): string[] => {
  if (!value) return [];
  if (Array.isArray(value)) {
    return value.map((item) => (typeof item === 'string' ? item : asText(item))).filter(Boolean);
  }
  if (typeof value === 'string') {
    return value.split(/\n|;|\.\s+/).map((item) => item.trim()).filter(Boolean);
  }
  return [];
};

const normalizeReport = (raw: any): LibertyReport => {
  const data = raw?.report || raw?.output || raw || {};
  const differentials = Array.isArray(data?.differential_diagnosis)
    ? data.differential_diagnosis
    : Array.isArray(data?.diagnoses)
      ? data.diagnoses
      : Array.isArray(data)
        ? data
        : [];
  const normalizedDifferentials = differentials.slice(0, 4).map((item: any) => ({
    name: item?.full_name || item?.name || item?.condition || item?.diagnosis || 'Clinical consideration',
    confidence: item?.confidence || item?.confidence_score || item?.likelihood,
    description: item?.description || item?.summary,
    reason: item?.reason || item?.rationale || item?.supporting_reason,
  }));
  const soap = data?.soap || data?.soap_note || data?.SOAP || {};
  return {
    summary: asText(
      data?.patient_summary || data?.summary || data?.share_report || data?.report_summary,
      'LibertyMD completed the AI Care intake and generated a doctor-ready report.'
    ),
    differentials: normalizedDifferentials,
    plan: listFrom(data?.plan || data?.care_plan || data?.assessment_plan || data?.recommendations).slice(0, 6),
    redFlags: listFrom(data?.red_flags || data?.warning_signs || data?.seek_care_if).slice(0, 6),
    soap: {
      subjective: asText(soap?.subjective || data?.subjective, 'Symptoms and history captured during chat.'),
      objective: asText(soap?.objective || data?.objective, 'No vitals or physical exam were directly measured in this AI consult.'),
      assessment: asText(soap?.assessment || data?.assessment || normalizedDifferentials.map((d) => d.name).join(', '), 'Assessment generated by the AI Care diagnosis workflow.'),
      plan: asText(soap?.plan || data?.plan || data?.care_plan, 'Follow the plan above and seek care urgently if red flags appear.'),
    },
  };
};

const HOW_IT_WORKS_ROTATION_MS = 5600;

const howItWorksSteps = [
  {
    title: 'Share your symptoms',
    eyebrow: 'Start naturally',
    description: 'Tell LibertyMD what you feel, when it began, and what worries you most. You do not need to know the medical words.',
    placeholder: 'Video placeholder: symptom entry and conversation start',
    icon: Sparkles,
  },
  {
    title: 'Focussed Follow-up',
    eyebrow: 'Only what matters',
    description: 'LibertyMD asks concise questions about timing, severity, history, and context, adapting each follow-up to your answers.',
    placeholder: 'Video placeholder: adaptive follow-up questions',
    icon: Activity,
  },
  {
    title: 'Safety Screen',
    eyebrow: 'Urgency checked early',
    description: 'Clinical guardrails look for warning signs throughout the conversation and clearly explain when urgent or emergency care is needed.',
    placeholder: 'Video placeholder: safety screening and escalation',
    icon: ShieldCheck,
  },
  {
    title: 'Doctor Ready Report',
    eyebrow: 'Context ready to share',
    description: 'Your answers become a structured summary with the symptom timeline, safety guidance, next steps, and a doctor-ready SOAP note.',
    placeholder: 'Video placeholder: doctor-ready report and handoff',
    icon: FileText,
  },
];

function LibertyMDHowItWorksTabs() {
  const [activeStep, setActiveStep] = useState(0);
  const [isPaused, setIsPaused] = useState(false);
  const [cycleKey, setCycleKey] = useState(0);
  const tabRailRef = useRef<HTMLDivElement | null>(null);
  const tabRefs = useRef<(HTMLButtonElement | null)[]>([]);
  const currentStep = howItWorksSteps[activeStep];

  useEffect(() => {
    if (isPaused || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

    const timer = window.setTimeout(() => {
      setActiveStep((current) => (current + 1) % howItWorksSteps.length);
      setCycleKey((current) => current + 1);
    }, HOW_IT_WORKS_ROTATION_MS);

    return () => window.clearTimeout(timer);
  }, [activeStep, cycleKey, isPaused]);

  useEffect(() => {
    const rail = tabRailRef.current;
    const tab = tabRefs.current[activeStep];
    if (!rail || !tab) return;

    const railRect = rail.getBoundingClientRect();
    const tabRect = tab.getBoundingClientRect();
    rail.scrollTo({
      left: rail.scrollLeft + tabRect.left - railRect.left - (rail.clientWidth - tabRect.width) / 2,
      behavior: 'smooth',
    });
  }, [activeStep]);

  const selectStep = (index: number) => {
    setActiveStep(index);
    setCycleKey((current) => current + 1);
  };

  const resumeRotation = () => {
    setIsPaused(false);
    setCycleKey((current) => current + 1);
  };

  return (
    <div
      className="libertymd-content-shell mx-auto mt-12"
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={resumeRotation}
      onFocusCapture={() => setIsPaused(true)}
      onBlurCapture={resumeRotation}
    >
      <div
        ref={tabRailRef}
        role="tablist"
        aria-label="How LibertyMD works"
        className="libertymd-how-tabs flex snap-x snap-mandatory gap-4 overflow-x-auto border-b border-[#CAD8D0] pb-0 lg:grid lg:grid-cols-4 lg:gap-7"
      >
        {howItWorksSteps.map((step, index) => {
          const Icon = step.icon;
          const isActive = index === activeStep;

          return (
            <button
              key={step.title}
              ref={(node) => { tabRefs.current[index] = node; }}
              type="button"
              role="tab"
              id={`libertymd-how-tab-${index}`}
              aria-controls="libertymd-how-panel"
              aria-selected={isActive}
              tabIndex={isActive ? 0 : -1}
              onClick={() => selectStep(index)}
              className={`relative flex min-w-[12.5rem] snap-start items-center gap-3 pb-5 text-left transition-colors sm:min-w-[15rem] lg:min-w-0 ${
                isActive ? 'text-[#17325F]' : 'text-[#8290A0] hover:text-[#334155]'
              }`}
            >
              <Icon className={`h-5 w-5 shrink-0 ${isActive ? 'text-[#2563EB]' : 'text-[#A9B5C0]'}`} />
              <span className="text-sm font-bold leading-5">{step.title}</span>
              <span aria-hidden="true" className="absolute inset-x-0 bottom-0 h-[3px] overflow-hidden bg-[#D8E2DC]">
                {index < activeStep && <span className="block h-full w-full bg-[#8AAEEB]" />}
                {isActive && (
                  <span
                    key={`${activeStep}-${cycleKey}`}
                    className="libertymd-how-progress block h-full w-full bg-[#2563EB]"
                    style={{
                      animationDuration: `${HOW_IT_WORKS_ROTATION_MS}ms`,
                      animationPlayState: isPaused ? 'paused' : 'running',
                    }}
                  />
                )}
              </span>
            </button>
          );
        })}
      </div>

      <div
        id="libertymd-how-panel"
        role="tabpanel"
        aria-labelledby={`libertymd-how-tab-${activeStep}`}
        className="mt-10 grid items-center gap-9 lg:grid-cols-[minmax(17rem,0.58fr)_minmax(34rem,1.42fr)] lg:gap-[clamp(3rem,6vw,7rem)]"
      >
        <div className="order-2 mx-auto max-w-lg text-center lg:order-1 lg:mx-0 lg:text-left">
          <p className="text-xs font-bold uppercase text-[#2563EB]">Step {String(activeStep + 1).padStart(2, '0')} · {currentStep.eyebrow}</p>
          <h3 className="mt-4 font-serif text-3xl font-semibold leading-tight text-[#111827] sm:text-4xl">{currentStep.title}</h3>
          <p className="mt-5 text-sm leading-7 text-[#5B6472] sm:text-base">{currentStep.description}</p>
        </div>

        <div className="order-1 lg:order-2">
          <div className="relative aspect-video overflow-hidden rounded-lg border border-[#C9D9E9] bg-[linear-gradient(145deg,rgba(255,255,255,0.92),rgba(225,238,251,0.82)_55%,rgba(225,245,239,0.9))] shadow-[0_24px_70px_rgba(23,50,95,0.11)]">
            <div className="absolute inset-0 opacity-[0.16] [background-image:linear-gradient(rgba(37,99,235,0.18)_1px,transparent_1px),linear-gradient(90deg,rgba(37,99,235,0.18)_1px,transparent_1px)] [background-size:32px_32px]" />
            <div className="relative flex h-full flex-col items-center justify-center px-6 text-center">
              <span className="inline-flex h-14 w-14 items-center justify-center rounded-full border border-white/90 bg-white/70 text-[#2563EB] shadow-[0_12px_34px_rgba(37,99,235,0.13)] backdrop-blur-md">
                <Video className="h-6 w-6" />
              </span>
              <p className="mt-5 text-sm font-semibold text-[#435775] sm:text-base">{currentStep.placeholder}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function LibertyMDApp({ onBack }: LibertyMDAppProps) {
  const [region] = useState<'EU' | 'US'>('EU');
  const [input, setInput] = useState('');
  const [phase, setPhase] = useState<ChatPhase>('initial');
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [demographics, setDemographics] = useState({ age: '', sex: '' });
  const [report, setReport] = useState<LibertyReport | null>(null);
  const [error, setError] = useState('');
  const [safetyNotice, setSafetyNotice] = useState('');
  const [isAnonymous, setIsAnonymous] = useState(true);
  const [greetingName, setGreetingName] = useState('');
  const [profile, setProfile] = useState<LibertyMDProfile | null>(null);
  const [history, setHistory] = useState<LibertyMDHistoryItem[]>([]);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isReportGateOpen, setIsReportGateOpen] = useState(false);
  const [isAccountLoading, setIsAccountLoading] = useState(true);
  const [isAuthBusy, setIsAuthBusy] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: '1',
      sender: 'ai',
      kind: 'system',
      text: `Tell me what is happening, when it started, and what worries you most. I'll ask a few focused questions and flag urgent warning signs.`
    }
  ]);
  const [isTyping, setIsTyping] = useState(false);
  const [selectedTab, setSelectedTab] = useState<'chat' | 'doctors'>('chat');
  const [isFloatingComposerVisible, setIsFloatingComposerVisible] = useState(false);
  const [isHeroInputFocused, setIsHeroInputFocused] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement | null>(null);
  const chatPanelRef = useRef<HTMLDivElement | null>(null);
  const logoDockHeadlineRef = useRef<HTMLHeadingElement | null>(null);
  const heroComposerRef = useRef<HTMLFormElement | null>(null);
  const heroSymptomsRef = useRef<HTMLTextAreaElement | null>(null);
  const hasActiveConsultRef = useRef(false);
  const demographicsReady = demographics.age.trim() && demographics.sex;
  const shouldShowFloatingComposer = isFloatingComposerVisible && phase === 'initial';
  const identityPromiseRef = useRef<Promise<unknown> | null>(null);

  useEffect(() => {
    const composer = heroComposerRef.current;
    if (!composer) return undefined;

    const observer = new IntersectionObserver(
      ([entry]) => {
        setIsFloatingComposerVisible(!entry.isIntersecting && entry.boundingClientRect.bottom <= 0);
      },
      { threshold: [0, 0.01] }
    );

    observer.observe(composer);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    if (!hasActiveConsultRef.current) return;
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }, [messages, isTyping, report]);

  const ensureIdentity = async () => {
    const { data: sessionData } = await supabase.auth.getSession();
    if (sessionData.session) return sessionData.session;
    if (!identityPromiseRef.current) {
      identityPromiseRef.current = supabase.auth.signInAnonymously().then(({ data, error: authError }) => {
        if (authError || !data.session) throw authError || new Error('Unable to create a private LibertyMD session.');
        return data.session;
      });
    }
    return identityPromiseRef.current;
  };

  const invokeCareProxy = async (body: Record<string, unknown>) => {
    await ensureIdentity();
    const { data, error: fnError } = await supabase.functions.invoke('libertymd-care-proxy', {
      body: { region, ...body }
    });
    if (fnError) throw fnError;
    return data;
  };

  const refreshHistory = async () => {
    if (isAnonymous) return;
    setIsAccountLoading(true);
    try {
      const data = await invokeCareProxy({ action: 'get_history' });
      setHistory(Array.isArray(data?.history) ? data.history : []);
    } catch (historyError) {
      console.error('Unable to refresh LibertyMD history', historyError);
    } finally {
      setIsAccountLoading(false);
    }
  };

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      setIsAccountLoading(true);
      try {
        const params = new URLSearchParams(window.location.search);
        const oauthConsultation = params.get('consultation');
        const action = params.get('auth') === 'complete' ? 'sync_identity' : 'bootstrap';
        const data = await invokeCareProxy({ action, consultation_id: oauthConsultation || undefined });
        if (cancelled) return;
        setIsAnonymous(Boolean(data?.is_anonymous));
        setGreetingName(String(data?.greeting_name || ''));
        setProfile(data?.profile || null);
        if (data?.profile?.age || data?.profile?.sex_at_birth) {
          setDemographics({
            age: data.profile.age ? String(data.profile.age) : '',
            sex: String(data.profile.sex_at_birth || ''),
          });
        }
        setHistory(Array.isArray(data?.history) ? data.history : []);
        if (data?.report && oauthConsultation) {
          setSessionId(oauthConsultation);
          setReport(normalizeReport(data.report));
          setPhase('report_ready');
          hasActiveConsultRef.current = true;
          const consult = await invokeCareProxy({ action: 'get_consultation', consultation_id: oauthConsultation });
          if (!cancelled && Array.isArray(consult?.messages)) {
            setMessages(consult.messages.map((item: any, index: number) => ({
              id: `${oauthConsultation}-${index}`,
              sender: item.role === 'user' ? 'user' : 'ai',
              text: item.content,
              options: Array.isArray(item.options) ? item.options : [],
              kind: item.message_type === 'safety' ? 'emergency' : item.message_type === 'report_gate' ? 'report' : 'normal',
            })));
          }
        } else if (data?.greeting_name) {
          setMessages([{
            id: '1',
            sender: 'ai',
            kind: 'system',
            text: `Hi ${data.greeting_name}, tell me what is happening, when it started, and what worries you most.`,
          }]);
        }
        if (params.has('auth')) {
          window.history.replaceState({}, '', window.location.pathname);
        }
      } catch (bootstrapError) {
        if (!cancelled) setError(bootstrapError instanceof Error ? bootstrapError.message : 'Unable to initialize LibertyMD.');
      } finally {
        if (!cancelled) setIsAccountLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const beginConsultation = async (symptom: string) => {
    setIsTyping(true);
    setError('');
    setSafetyNotice('');
    try {
      const data = await invokeCareProxy({ action: 'start_consultation', message: symptom });
      if (!data?.consultation_id) throw new Error('Unable to start LibertyMD consultation.');
      setSessionId(data.consultation_id);
      if (data?.emergency) {
        setPhase('emergency_end');
        setMessages(prev => [...prev, {
          id: `${Date.now()}-emergency`,
          sender: 'ai',
          kind: 'emergency',
          text: data.message || 'These symptoms may be an emergency. Seek emergency care now.',
        }]);
        return;
      }
      setPhase('demographics_required');
      if (data?.safety?.message) setSafetyNotice(String(data.safety.message));
      setMessages(prev => [...prev, {
        id: `${Date.now()}-demographics`,
        sender: 'ai',
        kind: 'system',
        text: data.acknowledgement || 'I’m sorry you are dealing with that. First, what is the patient’s age and sex assigned at birth?',
      }]);
    } catch (startError) {
      setError(startError instanceof Error ? startError.message : 'The LibertyMD workflow is temporarily unavailable.');
      setPhase('error');
    } finally {
      setIsTyping(false);
    }
  };

  const sendToWorkflow = async (text: string, activeSessionId?: string) => {
    const sid = activeSessionId || sessionId;
    if (!sid) return;
    setIsTyping(true);
    setError('');
    try {
      const clientMessageId = crypto.randomUUID();
      let data: any = null;
      let lastError: unknown = null;
      for (let attempt = 0; attempt < 2; attempt += 1) {
        try {
          data = await invokeCareProxy({
            action: 'send_message',
            consultation_id: sid,
            message: text,
            client_message_id: clientMessageId,
          });
          lastError = null;
          break;
        } catch (invokeError) {
          lastError = invokeError;
          if (attempt === 0) await new Promise(resolve => window.setTimeout(resolve, 500));
        }
      }
      if (lastError) throw lastError;

      if (data?.emergency) {
        setPhase('emergency_end');
        setMessages(prev => [...prev, {
          id: `${Date.now()}-emergency`,
          sender: 'ai',
          kind: 'emergency',
          text: data.message || 'These symptoms may be an emergency. Call emergency services or go to the ER now.',
        }]);
        return;
      }

      if (data?.clinical_review_needed) {
        setPhase('clinical_review_needed');
        setMessages(prev => [...prev, {
          id: `${Date.now()}-review`,
          sender: 'ai',
          kind: 'system',
          text: data.message || 'A reliable report could not be generated. Please continue with a licensed clinician.',
        }]);
        return;
      }

      if (data?.report_ready) {
        if (data?.auth_required) {
          setPhase('report_gate');
          setIsReportGateOpen(true);
        } else if (data?.report) {
          setReport(normalizeReport(data.report));
          setPhase('report_ready');
          await refreshHistory();
        }
        setMessages(prev => [...prev, {
          id: `${Date.now()}-report`,
          sender: 'ai',
          kind: 'report',
          text: data?.auth_required
            ? 'Your LibertyMD report is ready. Link Google to save it, or continue without saving.'
            : 'Your LibertyMD report is ready and saved in your consultation history.',
        }]);
        return;
      }

      setPhase('intake');
      setSafetyNotice(data?.safety?.message ? String(data.safety.message) : '');
      setMessages(prev => [...prev, {
        id: `${Date.now()}-ai`,
        sender: 'ai',
        text: data?.next_question || 'Could you tell me more about that?',
        options: Array.isArray(data?.options) ? data.options : [],
      }]);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'The LibertyMD AI Care workflow is temporarily unavailable.';
      setError(message);
      setPhase('error');
      setMessages(prev => [...prev, {
        id: `${Date.now()}-error`,
        sender: 'ai',
        kind: 'system',
        text: 'I could not reach the AI Care workflow. Please try again in a moment.',
      }]);
    } finally {
      setIsTyping(false);
    }
  };

  const submitDemographics = async () => {
    if (!sessionId || !demographicsReady || isTyping) return;
    setIsTyping(true);
    setError('');
    try {
      const data = await invokeCareProxy({
        action: 'save_demographics',
        consultation_id: sessionId,
        age: Number(demographics.age),
        sex_at_birth: demographics.sex,
      });
      setProfile(prev => ({ ...prev, age: Number(demographics.age), sex_at_birth: demographics.sex }));
      setPhase('intake');
      setMessages(prev => [...prev,
        {
          id: `${Date.now()}-demographic-answer`,
          sender: 'user',
          text: `Age ${demographics.age}; ${demographics.sex}`,
        },
        {
          id: `${Date.now()}-first-question`,
          sender: 'ai',
          text: data?.next_question || 'When did this symptom begin?',
          options: Array.isArray(data?.options) ? data.options : [],
        },
      ]);
    } catch (demographicsError) {
      setError(demographicsError instanceof Error ? demographicsError.message : 'Unable to save the clinical context.');
      setPhase('demographics_required');
    } finally {
      setIsTyping(false);
    }
  };

  const handleSend = (textToSend?: string) => {
    const text = (textToSend || input).trim();
    if (!text || isTyping || ['demographics_required', 'report_gate', 'report_ready', 'emergency_end', 'clinical_review_needed'].includes(phase)) return;

    hasActiveConsultRef.current = true;
    setInput('');
    setReport(null);
    setMessages(prev => [...prev, {
      id: Date.now().toString(),
      sender: 'user',
      text
    }]);
    chatPanelRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    if (!sessionId || phase === 'initial' || phase === 'error') void beginConsultation(text);
    else void sendToWorkflow(text);
  };

  const startGoogleLink = async () => {
    setIsAuthBusy(true);
    setError('');
    try {
      await ensureIdentity();
      const query = new URLSearchParams({ auth: 'complete' });
      if (sessionId) query.set('consultation', sessionId);
      const { error: linkError } = await supabase.auth.linkIdentity({
        provider: 'google',
        options: { redirectTo: `${window.location.origin}/liberty-md?${query.toString()}` },
      });
      if (linkError) throw linkError;
    } catch (linkError) {
      setError(linkError instanceof Error ? linkError.message : 'Unable to start Google sign in.');
      setIsAuthBusy(false);
    }
  };

  const skipReportGate = async () => {
    if (!sessionId) return;
    setIsAuthBusy(true);
    try {
      const data = await invokeCareProxy({ action: 'release_report', consultation_id: sessionId, mode: 'skip' });
      setReport(normalizeReport(data.report));
      setPhase('report_ready');
      setIsReportGateOpen(false);
    } catch (releaseError) {
      setError(releaseError instanceof Error ? releaseError.message : 'Unable to release the report.');
    } finally {
      setIsAuthBusy(false);
    }
  };

  const loadConsultation = async (consultationId: string) => {
    setIsAccountLoading(true);
    try {
      const data = await invokeCareProxy({ action: 'get_consultation', consultation_id: consultationId });
      setSessionId(consultationId);
      setMessages((data.messages || []).map((item: any, index: number) => ({
        id: `${consultationId}-${index}`,
        sender: item.role === 'user' ? 'user' : 'ai',
        text: item.content,
        options: Array.isArray(item.options) ? item.options : [],
        kind: item.message_type === 'safety' ? 'emergency' : item.message_type === 'report_gate' ? 'report' : 'normal',
      })));
      if (data.report) {
        setReport(normalizeReport(data.report));
        setPhase('report_ready');
      } else {
        const status = data.consultation?.status;
        const nextPhase = status === 'awaiting_demographics' ? 'demographics_required' : status === 'report_pending_auth' ? 'report_gate' : status === 'emergency_stopped' ? 'emergency_end' : 'intake';
        setPhase(nextPhase);
        setIsReportGateOpen(nextPhase === 'report_gate');
      }
      hasActiveConsultRef.current = true;
      setIsMenuOpen(false);
      chatPanelRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    } catch (historyError) {
      setError(historyError instanceof Error ? historyError.message : 'Unable to load the consultation.');
    } finally {
      setIsAccountLoading(false);
    }
  };

  const resetConsult = () => {
    hasActiveConsultRef.current = false;
    setInput('');
    setPhase('initial');
    setSessionId(null);
    setReport(null);
    setError('');
    setSafetyNotice('');
    setIsReportGateOpen(false);
    setDemographics({ age: profile?.age ? String(profile.age) : '', sex: profile?.sex_at_birth || '' });
    setMessages([
      {
        id: '1',
        sender: 'ai',
        kind: 'system',
        text: `${greetingName ? `Hi ${greetingName}, ` : ''}tell me what is happening, when it started, and what worries you most.`
      }
    ]);
  };

  const dockZoneRef = useRef<HTMLDivElement | null>(null);
  const activeOptions = messages[messages.length - 1]?.options || [];
  const isComposerLocked = isTyping || ['demographics_required', 'report_gate', 'report_ready', 'emergency_end', 'clinical_review_needed'].includes(phase);
  return (
    <div
      className="min-h-screen text-center text-[#111827] font-sans selection:bg-[#2563EB] selection:text-white [&_input]:text-center [&_select]:text-center [&_textarea]:text-center"
      style={{
        background:
          'linear-gradient(180deg, #FBFCF9 0%, #F5F9FF 34%, #F3F8F2 66%, #EFF6FF 100%)',
      }}
    >
      <main>
        <section className="libertymd-page-gutter relative z-10 flex min-h-[100svh] flex-col overflow-visible">
          <div className="absolute inset-0 -z-10 bg-[linear-gradient(180deg,rgba(255,255,255,0.94)_0%,rgba(247,250,255,0.9)_54%,rgba(240,248,243,0.96)_100%)]" />

          <header className="libertymd-hero-header libertymd-shell flex h-16 shrink-0 items-center justify-between">
            <a
              href="/liberty-md"
              aria-label="LibertyMD home"
              className="inline-flex items-center gap-2 font-serif text-xl font-semibold text-[#111827] transition-colors hover:text-[#2563EB] sm:gap-2.5 sm:text-2xl"
            >
              <img
                src="/images/libertymd-logo-mark.svg"
                alt=""
                aria-hidden="true"
                className="h-8 w-8 shrink-0 object-contain sm:h-9 sm:w-9"
              />
              LibertyMD
            </a>

            <div className="flex items-center gap-3 text-sm font-semibold text-[#334155] sm:gap-5">
              {!isAnonymous && greetingName && <span className="hidden sm:inline">Hi, {greetingName}</span>}
              <button
                type="button"
                aria-label="Open profile and consultation history"
                onClick={() => {
                  setIsMenuOpen(true);
                  if (!isAnonymous) void refreshHistory();
                }}
                className="inline-flex h-9 w-9 items-center justify-center text-[#111827] transition-colors hover:text-[#2563EB]"
              >
                <Menu className="h-5 w-5" />
              </button>
            </div>
          </header>

          <div className="libertymd-hero-content libertymd-shell flex flex-1 flex-col items-center justify-center pb-8 text-center sm:pb-0 [@media(max-height:700px)]:pb-0">
            <style>
              {`
                @keyframes libertymd-proof-reveal {
                  from { opacity: 0; transform: translateY(5px); }
                  to { opacity: 1; transform: translateY(0); }
                }

                .libertymd-tagline-word {
                  opacity: 0;
                  animation: libertymd-proof-reveal 520ms cubic-bezier(0.22, 1, 0.36, 1) forwards;
                }

                @keyframes libertymd-placeholder-dot-pulse {
                  0%, 62%, 100% { opacity: 0.24; transform: translateY(0); }
                  28% { opacity: 1; transform: translateY(-2px); }
                }

                .libertymd-placeholder-dot {
                  display: inline-block;
                  animation: libertymd-placeholder-dot-pulse 1.5s ease-in-out infinite;
                  color: #2563EB;
                  will-change: opacity, transform;
                }

                .libertymd-start-chat-cta {
                  box-shadow:
                    inset 0 1px 0 rgba(255, 255, 255, 0.44),
                    inset 0 -1px 0 rgba(15, 54, 153, 0.28),
                    0 11px 26px rgba(37, 99, 235, 0.34);
                  transform: translateY(0);
                }

                .libertymd-start-chat-cta::before {
                  content: '';
                  position: absolute;
                  top: -35%;
                  bottom: -35%;
                  left: -42%;
                  width: 24%;
                  background: linear-gradient(
                    105deg,
                    rgba(255, 255, 255, 0) 0%,
                    rgba(255, 255, 255, 0.16) 30%,
                    rgba(255, 255, 255, 0.62) 50%,
                    rgba(255, 255, 255, 0.16) 70%,
                    rgba(255, 255, 255, 0) 100%
                  );
                  filter: blur(1px);
                  pointer-events: none;
                  transform: translateX(-180%) skewX(-16deg);
                  will-change: transform;
                }

                @keyframes libertymd-start-chat-satin-shine {
                  0% { transform: translateX(-180%) skewX(-16deg); }
                  18% { transform: translateX(700%) skewX(-16deg); }
                  100% { transform: translateX(700%) skewX(-16deg); }
                }

                @keyframes libertymd-start-chat-hover-shine {
                  from { transform: translateX(-180%) skewX(-16deg); }
                  to { transform: translateX(700%) skewX(-16deg); }
                }

                .libertymd-start-chat-cta--waiting::before {
                  animation: libertymd-start-chat-satin-shine 9.6s cubic-bezier(0.4, 0, 0.2, 1) 1.2s infinite;
                }

                .libertymd-start-chat-cta:hover {
                  background-color: #1D5FE2;
                  box-shadow:
                    inset 0 1px 0 rgba(255, 255, 255, 0.5),
                    inset 0 -1px 0 rgba(15, 54, 153, 0.3),
                    0 13px 30px rgba(37, 99, 235, 0.4);
                }

                .libertymd-start-chat-cta:hover::before {
                  animation: libertymd-start-chat-hover-shine 1.45s cubic-bezier(0.4, 0, 0.2, 1) 1;
                }

                .libertymd-start-chat-cta:active {
                  transform: translateY(1px) scale(0.99);
                  box-shadow:
                    inset 0 1px 0 rgba(255, 255, 255, 0.34),
                    inset 0 -1px 0 rgba(15, 54, 153, 0.34),
                    0 7px 18px rgba(37, 99, 235, 0.3);
                }

                .libertymd-start-chat-arrow {
                  transition: transform 220ms cubic-bezier(0.22, 1, 0.36, 1);
                }

                .libertymd-start-chat-cta:hover .libertymd-start-chat-arrow {
                  transform: translateX(3px);
                }

                @media (prefers-reduced-motion: reduce) {
                  .libertymd-start-chat-cta,
                  .libertymd-start-chat-cta::before,
                  .libertymd-start-chat-arrow,
                  .libertymd-tagline-word,
                  .libertymd-placeholder-dot {
                    animation: none !important;
                    transform: none !important;
                  }

                  .libertymd-tagline-word,
                  .libertymd-placeholder-dot {
                    opacity: 1 !important;
                  }
                }
              `}
            </style>

            <div className="libertymd-hero-wordmark flex items-center justify-center gap-2.5 sm:gap-4">
              <img
                src="/images/libertymd-logo-mark.svg"
                alt=""
                aria-hidden="true"
                className="libertymd-hero-wordmark-icon h-9 w-9 shrink-0 translate-y-[2px] object-contain sm:h-14 sm:w-14 [@media(max-height:700px)]:h-8 [@media(max-height:700px)]:w-8"
              />
              <h1 className="libertymd-hero-title font-serif text-[56px] font-semibold leading-none text-[#111827] sm:text-7xl [@media(max-height:700px)]:whitespace-nowrap [@media(max-height:700px)]:text-5xl">
                LibertyMD
              </h1>
            </div>
            <p className="libertymd-hero-value mt-3 text-base font-semibold leading-6 text-[#334155] sm:text-lg">
              Clinically verified guidance for your symptoms.
            </p>
            <p
              className="libertymd-hero-tagline mt-2 flex min-h-6 flex-wrap items-center justify-center gap-x-2 text-sm font-bold text-[#17325F] sm:gap-x-3 sm:text-base"
              aria-label="Free, Anonymous, Built by Doctors"
            >
              {['Free', 'Anonymous', 'Built by Doctors'].map((phrase, index) => (
                <span
                  key={phrase}
                  className="libertymd-tagline-word inline-flex items-center gap-2 sm:gap-3"
                  style={{ animationDelay: `${220 + index * 120}ms` }}
                >
                  {index > 0 && (
                    <span aria-hidden="true" className="text-[#2563EB]">
                      •
                    </span>
                  )}
                  <span>{phrase}</span>
                </span>
              ))}
            </p>

            <LibertyMDPremiumLogo
              active={phase === 'initial'}
              dockHeadlineRef={logoDockHeadlineRef}
              className="z-10 mt-[var(--libertymd-gap-tagline-logo)] mb-4 sm:mb-[var(--libertymd-gap-pedestal-input)]"
            />

            <div className="libertymd-composer-width relative z-20">
              <form
                ref={heroComposerRef}
                onSubmit={(event) => {
                  event.preventDefault();
                  if (!input.trim()) {
                    heroSymptomsRef.current?.focus();
                    return;
                  }
                  handleSend();
                }}
                className="libertymd-hero-composer relative w-full rounded-[20px] border-[1.5px] border-[#BFD0EE] bg-white/[0.94] p-5 pt-7 text-center shadow-[0_18px_48px_rgba(37,99,235,0.16),0_4px_14px_rgba(15,23,42,0.1),inset_0_1px_0_rgba(255,255,255,0.95)] ring-1 ring-[#2563EB]/10 backdrop-blur-md sm:bg-white/[0.94] sm:shadow-[0_18px_60px_rgba(15,23,42,0.1),0_4px_18px_rgba(37,99,235,0.08)]"
              >
                <label
                  htmlFor="libertymd-hero-symptoms"
                  className="absolute -top-4 left-5 rounded-full bg-[#E5FFB8] px-4 py-2 text-sm font-black text-[#111827] shadow-[0_4px_12px_rgba(91,125,44,0.08)] sm:left-8 sm:px-5 sm:text-base [@media(max-height:700px)]:left-5 [@media(max-height:700px)]:px-4 [@media(max-height:700px)]:py-2 [@media(max-height:700px)]:text-xs"
                >
                  What brings you in?
                </label>
                <div className="libertymd-hero-composer-field relative w-full">
                  {!input && !isHeroInputFocused && (
                    <div
                      aria-hidden="true"
                      className="pointer-events-none absolute inset-x-0 top-0 px-4 py-2 !text-left text-base leading-7 text-[#64748B] sm:px-5 sm:py-4 sm:text-xl [@media(max-height:700px)]:px-3 [@media(max-height:700px)]:py-1 [@media(max-height:700px)]:text-xs [@media(max-height:700px)]:leading-5"
                    >
                      <span className="sm:hidden">Describe your symptoms</span>
                      <span className="hidden sm:inline">Describe symptom or ask any health questions</span>
                      <span className="ml-0.5 inline-flex" aria-hidden="true">
                        {[0, 1, 2].map((dot) => (
                          <span
                            key={dot}
                            className="libertymd-placeholder-dot"
                            style={{ animationDelay: `${dot * 180}ms` }}
                          >
                            .
                          </span>
                        ))}
                      </span>
                    </div>
                  )}
                  <textarea
                    ref={heroSymptomsRef}
                    id="libertymd-hero-symptoms"
                    aria-label="Describe your symptoms or ask a health question"
                    rows={3}
                    value={input}
                    onChange={(event) => setInput(event.target.value)}
                    onFocus={() => setIsHeroInputFocused(true)}
                    onBlur={() => setIsHeroInputFocused(false)}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter' && !event.shiftKey) {
                        event.preventDefault();
                        handleSend();
                      }
                    }}
                    className="libertymd-hero-symptoms h-full min-h-0 w-full resize-none overflow-y-auto bg-transparent px-4 py-2 !text-left text-base leading-7 text-[#334155] caret-[#2563EB] outline-none sm:px-5 sm:py-4 sm:text-xl [@media(max-height:700px)]:px-3 [@media(max-height:700px)]:py-1 [@media(max-height:700px)]:text-xs [@media(max-height:700px)]:leading-5"
                  />
                </div>
                <button
                  type="submit"
                  aria-label={input.trim() ? 'Start LibertyMD chat' : 'Start by describing your symptoms'}
                  className={`libertymd-start-chat-cta ${!input.trim() ? 'libertymd-start-chat-cta--waiting' : ''} absolute bottom-5 left-5 right-5 isolate inline-flex h-[52px] cursor-pointer items-center justify-center gap-3 overflow-hidden rounded-full bg-[#2563EB] px-8 text-base font-bold text-white ring-1 ring-white/60 transition-[background-color,box-shadow,transform] duration-200 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#93C5FD] sm:bottom-5 sm:left-auto sm:right-5 sm:h-14 sm:w-64 [@media(max-height:700px)]:bottom-4 [@media(max-height:700px)]:left-4 [@media(max-height:700px)]:right-4 [@media(max-height:700px)]:h-12 [@media(max-height:700px)]:w-auto`}
                >
                  <span className="relative z-10">Start chat</span>
                  <ArrowRight className="libertymd-start-chat-arrow relative z-10 h-5 w-5" />
                </button>
              </form>

              <div className="libertymd-hero-trust-row mt-2 flex flex-row items-center justify-between gap-2 text-xs font-medium text-[#626262] sm:text-sm [@media(max-height:700px)]:mt-0 [@media(max-height:700px)]:gap-1">
                <div className="flex flex-nowrap items-center justify-start gap-2 [@media(max-height:700px)]:gap-1">
                  <span>4.5</span>
                  <span className="inline-flex h-4 w-4 items-center justify-center bg-[#169B52] sm:hidden" aria-hidden="true">
                    <Star className="h-3 w-3 fill-white text-white" />
                  </span>
                  <span className="hidden gap-0.5 sm:inline-flex" aria-label="4.5 out of 5 rating">
                    {[0, 1, 2, 3, 4].map((item) => (
                      <span
                        key={item}
                        className={`inline-flex h-5 w-5 items-center justify-center [@media(max-height:700px)]:h-4 [@media(max-height:700px)]:w-4 ${
                          item === 4
                            ? 'bg-[linear-gradient(90deg,#169B52_0%,#169B52_50%,#D4D4D4_50%,#D4D4D4_100%)]'
                            : 'bg-[#169B52]'
                        }`}
                      >
                        <Star className="h-3.5 w-3.5 fill-white text-white [@media(max-height:700px)]:h-3 [@media(max-height:700px)]:w-3" />
                      </span>
                    ))}
                  </span>
                </div>
                <span
                  className="inline-flex shrink-0 items-center gap-1 whitespace-nowrap font-semibold text-[#17325F] sm:gap-2"
                  aria-label="Trusted by more than 1,000,000 users"
                >
                  <UsersRound className="h-4 w-4 shrink-0 text-[#17325F] sm:h-5 sm:w-5" aria-hidden="true" />
                  <span className="sm:hidden">1M+ users</span>
                  <span className="hidden sm:inline">Trusted by 1,000,000+ users</span>
                </span>
                <span className="inline-flex shrink-0 items-center gap-1 whitespace-nowrap text-[#17325F] sm:gap-2">
                  <ShieldCheck className="h-4 w-4 text-[#17325F] sm:h-5 sm:w-5" />
                  <span className="sm:hidden">HIPAA Private</span>
                  <span className="hidden sm:inline">HIPAA Compliant &amp; Private</span>
                </span>
              </div>
            </div>
          </div>

          <LibertyMDParticleWaveSeparator />
        </section>

        <section ref={chatPanelRef} className="libertymd-page-gutter relative z-0 bg-[linear-gradient(180deg,rgba(245,250,243,0.96),rgba(237,247,241,0.98))] pb-16 pt-[300px] sm:pt-[340px]">
          <div className="mx-auto max-w-3xl text-center">
            <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">From symptom to next step</p>
            <h2 ref={logoDockHeadlineRef} className="mt-3 text-4xl font-black leading-tight tracking-normal text-[#111827] sm:text-5xl">
              How LibertyMD works
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-base font-bold leading-7 text-[#17325F] sm:text-lg">
              Simple enough to use when you feel unwell.
            </p>
          </div>

          {phase === 'initial' ? (
            <LibertyMDHowItWorksTabs />
          ) : (
            <div className="libertymd-content-shell mx-auto mt-14 max-w-4xl text-center">
              <div className="min-h-[560px]">
              <div className="mb-4 flex items-center justify-between border-b border-[#DDE7D8] pb-3">
                <div className="flex items-center gap-2.5">
                  <span className="h-2.5 w-2.5 rounded-full bg-[#16A34A]" />
                  <span className="text-sm font-bold text-[#111827]">LibertyMD care assistant</span>
                  <span className="hidden text-xs text-[#64748B] sm:inline">Private session · {region}</span>
                </div>
                <button onClick={resetConsult} className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#64748B] hover:text-[#2563EB]">
                  <RotateCcw className="h-3.5 w-3.5" />
                  Reset
                </button>
              </div>

              <div className="space-y-5">
                {messages.map((message) => (
                  <div key={message.id} className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                    <div
                      className={`max-w-[88%] rounded-[20px] px-5 py-4 text-sm leading-7 shadow-[0_14px_40px_rgba(15,23,42,0.045)] ${
                        message.sender === 'user'
                          ? 'bg-[#5661F6] text-white'
                          : message.kind === 'emergency'
                          ? 'bg-[#FFF1F2] text-[#991B1B]'
                          : message.kind === 'report'
                          ? 'bg-white text-[#166534]'
                          : 'bg-white text-[#334155]'
                      }`}
                    >
                      {message.text}
                    </div>
                  </div>
                ))}

                {phase === 'demographics_required' && (
                  <LibertyMDDemographicsPrompt
                    age={demographics.age}
                    sex={demographics.sex}
                    loading={isTyping}
                    error={error}
                    onAgeChange={(age) => setDemographics(prev => ({ ...prev, age }))}
                    onSexChange={(sex) => setDemographics(prev => ({ ...prev, sex }))}
                    onSubmit={submitDemographics}
                  />
                )}

                {safetyNotice && phase !== 'emergency_end' && (
                  <div className="mx-auto max-w-2xl border-l-2 border-amber-500 bg-amber-50 px-4 py-3 text-left text-sm leading-6 text-amber-900">
                    {safetyNotice}
                  </div>
                )}

                {phase === 'report_gate' && !isReportGateOpen && (
                  <button
                    type="button"
                    onClick={() => setIsReportGateOpen(true)}
                    className="mx-auto inline-flex h-11 items-center justify-center rounded-full bg-libertymd-blue-600 px-6 text-sm font-bold text-white shadow-lg shadow-libertymd-blue-600/20 hover:bg-libertymd-blue-700"
                  >
                    View report options
                  </button>
                )}

                {error && phase !== 'demographics_required' && (
                  <div className="border-t border-[#FDE68A] pt-5 text-sm leading-6 text-[#92400E]">
                    {error}
                  </div>
                )}

                {isTyping && (
                  <div className="flex items-center gap-2 text-sm text-[#64748B]">
                    <Loader2 className="h-4 w-4 animate-spin text-[#5661F6]" />
                    Checking safety and generating the next clinical step...
                  </div>
                )}

                {report && (
                  <div className="border-t border-[#DDE7D8] pt-7">
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                      <div>
                        <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">Share LibertyMD Report</p>
                        <h3 className="mt-2 text-3xl font-black tracking-normal text-[#111827]">Assessment & Plan</h3>
                      </div>
                      <button
                        type="button"
                        onClick={() => setSelectedTab('doctors')}
                        className="w-max rounded-full bg-[#111827] px-5 py-2.5 text-sm font-bold text-white hover:bg-[#1F2937]"
                      >
                        Continue to a licensed doctor
                      </button>
                    </div>

                    <p className="mt-5 max-w-3xl text-base leading-8 text-[#334155]">{report.summary}</p>

                    {report.differentials.length > 0 && (
                      <div className="mt-8 space-y-5 border-t border-[#DDE7D8] pt-6">
                        <p className="text-xs font-bold uppercase tracking-normal text-[#64748B]">Clinical considerations</p>
                        {report.differentials.map((item, index) => (
                          <div key={`${item.name}-${index}`} className="border-b border-[#DDE7D8] pb-5">
                            <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                              <div>
                                <h4 className="font-bold text-[#111827]">{item.name}</h4>
                                {item.description && <p className="mt-1 text-sm leading-7 text-[#5B6472]">{item.description}</p>}
                                {item.reason && <p className="mt-2 text-xs leading-6 text-[#64748B]">{item.reason}</p>}
                              </div>
                              {item.confidence && <span className="text-xs font-bold text-[#2563EB]">{item.confidence}</span>}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    <div className="mt-8 grid gap-8 md:grid-cols-2">
                      <div>
                        <h4 className="text-sm font-black text-[#166534]">Care Plan</h4>
                        <ul className="mt-3 space-y-2 text-sm leading-7 text-[#334155]">
                          {(report.plan.length ? report.plan : ['Monitor symptoms, rest, hydrate, and follow up if symptoms worsen.']).map((item, index) => (
                            <li key={index}>- {item}</li>
                          ))}
                        </ul>
                      </div>
                      <div>
                        <h4 className="text-sm font-black text-[#991B1B]">Red Flags</h4>
                        <ul className="mt-3 space-y-2 text-sm leading-7 text-[#334155]">
                          {(report.redFlags.length ? report.redFlags : ['Seek urgent care for chest pain, trouble breathing, confusion, fainting, severe worsening pain, or symptoms that feel dangerous.']).map((item, index) => (
                            <li key={index}>- {item}</li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div className="mt-8 border-t border-[#DDE7D8] pt-6">
                      <h4 className="font-black text-[#111827]">SOAP Note</h4>
                      <div className="mt-4 grid gap-x-8 gap-y-5 md:grid-cols-2">
                        {[
                          ['Subjective', report.soap.subjective],
                          ['Objective', report.soap.objective],
                          ['Assessment', report.soap.assessment],
                          ['Plan', report.soap.plan]
                        ].map(([label, value]) => (
                          <div key={label}>
                            <p className="text-xs font-bold uppercase tracking-normal text-[#64748B]">{label}</p>
                            <p className="mt-2 whitespace-pre-line text-sm leading-7 text-[#334155]">{value}</p>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="mt-8 flex items-center gap-2 border-t border-[#DDE7D8] pt-5 text-sm text-[#5B6472]">
                      <ShieldCheck className="h-4 w-4 text-[#2563EB]" />
                      {isAnonymous ? 'Guest report available for seven days.' : 'Saved privately to your LibertyMD history.'}
                    </div>
                  </div>
                )}

                <div ref={messagesEndRef} />
              </div>

              <div className="mt-6 border-t border-[#DDE7D8] pt-4">
                {!isComposerLocked && activeOptions.length > 0 && (
                  <div className="mb-4 flex flex-wrap gap-x-4 gap-y-2">
                    {activeOptions.map((option) => (
                      <button
                        key={option}
                        type="button"
                        disabled={isTyping}
                        onClick={() => handleSend(option)}
                        className="text-center text-xs font-semibold leading-5 text-[#2563EB] hover:text-[#111827] disabled:opacity-50"
                      >
                        {option}
                      </button>
                    ))}
                  </div>
                )}

                <form
                  onSubmit={(event) => {
                    event.preventDefault();
                    handleSend();
                  }}
                  className="flex items-center gap-2 rounded-full border border-white bg-white/92 px-4 py-3 shadow-[0_16px_50px_rgba(37,99,235,0.07)] backdrop-blur-xl"
                >
                  <input
                    type="text"
                    value={input}
                    onChange={(event) => setInput(event.target.value)}
                    disabled={isComposerLocked}
                    placeholder={phase === 'report_ready' ? 'Report is ready above' : phase === 'report_gate' ? 'Unlock your report to continue' : 'Answer the follow-up question...'}
                    className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#94A3B8]"
                  />
                  <button
                    type="submit"
                    aria-label="Send message"
                    disabled={!input.trim() || isComposerLocked}
                    className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#5661F6] text-white hover:bg-[#4651E6] disabled:cursor-not-allowed disabled:opacity-40"
                  >
                    <Send className="h-4 w-4" />
                  </button>
                </form>
              </div>
            </div>
            </div>
          )}
        </section>

        <LibertyMDPhoneCareSection
          onStartChat={() => {
            window.scrollTo({ top: 0, behavior: 'smooth' });
            window.setTimeout(() => heroSymptomsRef.current?.focus(), 650);
          }}
        />

        {selectedTab === 'doctors' && (
          <section className="libertymd-page-gutter libertymd-section-spacing border-t border-[#E6EDE3] bg-[linear-gradient(180deg,rgba(251,252,248,0.98),rgba(239,246,255,0.72))]">
            <div className="libertymd-content-shell">
              <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">Licensed handoff</p>
              <h2 className="mx-auto mt-3 max-w-xl text-3xl font-black tracking-normal text-[#111827] sm:text-4xl">
                Continue with a doctor when you need one.
              </h2>
              <div className="mt-10 grid gap-8 md:grid-cols-3">
                {[
                  ['Dr. Elena Rostova, MD', 'Urgent Care', '9 mins'],
                  ['Dr. Rajiv Patel, MD', 'Internal Medicine', '14 mins'],
                  ['Dr. Barry Pevner, MD', 'Family Medicine', '18 mins']
                ].map(([name, specialty, wait]) => (
                  <div key={name} className="border-t border-[#DDE7D8] pt-5">
                    <p className="text-xs font-bold uppercase tracking-normal text-[#64748B]">Available in {wait}</p>
                    <h3 className="mt-3 text-lg font-black text-[#111827]">{name}</h3>
                    <p className="mt-1 text-sm font-semibold text-[#2563EB]">{specialty}</p>
                    <p className="mt-3 text-sm leading-7 text-[#5B6472]">
                      Can review the AI report and advise next steps for {region === 'EU' ? '€39' : '$39'}.
                    </p>
                    <button className="mt-4 rounded-full bg-[#5661F6] px-5 py-2.5 text-sm font-bold text-white hover:bg-[#4651E6]">
                      Start visit
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </section>
        )}

        <LibertyMDPricingSection
          onStartChat={() => {
            window.scrollTo({ top: 0, behavior: 'smooth' });
            window.setTimeout(() => heroSymptomsRef.current?.focus(), 650);
          }}
        />

        {/* Ambient Clinical Care Film — calm full-width band. Video edges are feathered and a soft
            glow sits behind so it melts into the surrounding sections instead of reading as a hard rectangle. */}
        <section className="libertymd-page-gutter libertymd-section-spacing relative overflow-hidden border-t border-[#E6EDE3] bg-[linear-gradient(180deg,rgba(245,250,243,0.96)_0%,rgba(248,250,247,0.97)_100%)]">
          <div className="mx-auto max-w-3xl text-center">
            <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">Human care</p>
            <h2 className="mx-auto mt-3 max-w-xl text-3xl font-black tracking-normal text-[#111827] sm:text-4xl">
              A doctor&rsquo;s attention, built in.
            </h2>
            <p className="mx-auto mt-4 max-w-lg text-sm leading-7 text-[#5B6472]">
              Every triage is designed to hand off cleanly to a licensed physician.
            </p>
          </div>
          <div className="relative mx-auto mt-10 w-full max-w-[80rem]">
            {/* Soft blue/peach glow matching the film's palette so the seams disappear */}
            <div
              aria-hidden="true"
              className="pointer-events-none absolute -inset-x-6 -inset-y-8 -z-0 bg-[radial-gradient(60%_60%_at_50%_50%,rgba(191,219,254,0.45),rgba(254,226,226,0.22)_55%,transparent_80%)] blur-2xl"
            />
            <div className="relative overflow-hidden rounded-3xl">
              <video
                className="w-full aspect-video object-cover [mask-image:linear-gradient(180deg,transparent_0%,#000_14%,#000_86%,transparent_100%)] [-webkit-mask-image:linear-gradient(180deg,transparent_0%,#000_14%,#000_86%,transparent_100%)]"
                autoPlay
                loop
                muted
                playsInline
                preload="metadata"
                poster="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/video/doctor-consult-poster.jpg"
                aria-label="Ambient LibertyMD film: a doctor gently examining a patient with a stethoscope in a soft, glowing style"
              >
                <source
                  src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/video/doctor-consult-loop.webm"
                  type="video/webm"
                />
                <source
                  src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/video/doctor-consult-loop.mp4"
                  type="video/mp4"
                />
              </video>
              {/* Left/right feather so the film blends into the page gutters on wide screens */}
              <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(90deg,rgba(247,250,245,0.6)_0%,transparent_11%,transparent_89%,rgba(247,250,245,0.6)_100%)]" />
            </div>
          </div>
        </section>

        <LibertyMDPatientStoriesSection />

        <LibertyMDHealthLibrarySection />

      </main>

      {phase === 'report_gate' && isReportGateOpen && (
        <LibertyMDReportGate
          loading={isAuthBusy}
          onGoogle={startGoogleLink}
          onSkip={skipReportGate}
          onClose={() => setIsReportGateOpen(false)}
        />
      )}

      <LibertyMDAccountDrawer
        open={isMenuOpen}
        isAnonymous={isAnonymous}
        displayName={profile?.display_name}
        email={profile?.email}
        avatarUrl={profile?.avatar_url}
        age={profile?.age}
        sexAtBirth={profile?.sex_at_birth}
        history={history}
        loading={isAccountLoading}
        onClose={() => setIsMenuOpen(false)}
        onSelectConsultation={loadConsultation}
      />

      <div
        aria-hidden={!shouldShowFloatingComposer}
        style={{ transitionTimingFunction: 'cubic-bezier(0.22, 1, 0.36, 1)' }}
        className={`pointer-events-none fixed inset-x-0 bottom-[max(14px,env(safe-area-inset-bottom))] z-[70] px-3 transition-[opacity,transform] duration-500 sm:px-6 ${
          shouldShowFloatingComposer ? 'translate-y-0 opacity-100' : 'translate-y-8 opacity-0'
        }`}
      >
        <form
          onSubmit={(event) => {
            event.preventDefault();
            if (!input.trim()) {
              const floatingInput = event.currentTarget.elements.namedItem('floating-health-question');
              if (floatingInput instanceof HTMLInputElement) floatingInput.focus();
              return;
            }
            handleSend();
          }}
          className={`pointer-events-auto mx-auto flex h-16 w-full max-w-[64rem] items-center gap-2 rounded-full border border-white/75 bg-white/[0.58] p-2 pl-5 shadow-[0_22px_65px_rgba(15,23,42,0.18),inset_0_1px_0_rgba(255,255,255,0.82)] backdrop-blur-2xl backdrop-saturate-150 transition-[background-color,box-shadow] hover:bg-white/[0.68] hover:shadow-[0_26px_75px_rgba(15,23,42,0.22),inset_0_1px_0_rgba(255,255,255,0.9)] sm:h-20 sm:pl-8 ${
            shouldShowFloatingComposer ? '' : 'pointer-events-none'
          }`}
        >
          <input
            name="floating-health-question"
            type="text"
            value={input}
            onChange={(event) => setInput(event.target.value)}
            disabled={isComposerLocked}
            placeholder="Ask about your health..."
            aria-label="Ask LibertyMD about your health"
            tabIndex={shouldShowFloatingComposer ? 0 : -1}
            className="min-w-0 flex-1 bg-transparent px-1 text-center text-sm font-medium text-[#0F172A] outline-none placeholder:text-[#64748B] sm:text-lg"
          />
          <button
            type="submit"
            aria-label="Send health question"
            tabIndex={shouldShowFloatingComposer ? 0 : -1}
            disabled={isComposerLocked}
            className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#2563EB] text-white shadow-[0_10px_24px_rgba(37,99,235,0.38)] transition-[background-color,box-shadow,transform] hover:bg-[#1D4ED8] hover:shadow-[0_13px_30px_rgba(37,99,235,0.45)] active:scale-95 disabled:cursor-not-allowed disabled:opacity-45 sm:h-16 sm:w-16"
          >
            <Send className="h-5 w-5 sm:h-6 sm:w-6" />
          </button>
        </form>
      </div>

      {/* Exact Doctronic-Style 3D Volumetric Ribbon Footer in Blue */}
      <footer className="relative mt-24 bg-gradient-to-b from-[#EFF6FF] via-[#F0F9FF] to-[#E0F2FE] text-[#0F172A] overflow-hidden min-h-[720px] flex flex-col justify-between">
        {/* Three.js WebGL 3D Silk Wave Ribbon (Blue Theme) */}
        <LibertyMDFooterRibbon />

        {/* Top Content: Links + Trust Badges */}
        <div className="relative z-10 max-w-7xl mx-auto px-6 sm:px-10 pt-16 w-full">
          <div className="flex flex-col lg:flex-row justify-between items-start gap-12">
            {/* Left Columns */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-8 text-xs font-medium text-[#334155]">
              <div className="space-y-4">
                <p className="font-semibold text-sm text-[#0F172A]">Clinical Care</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">Symptom Checker</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Urgent Care Specialist</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Primary Telehealth</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Prescription Refills</li>
                </ul>

                <p className="font-semibold text-sm text-[#0F172A] pt-4">Help & Privacy</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">FAQs</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">GDPR Privacy Policy</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">HIPAA Compliance</li>
                </ul>
              </div>

              <div className="space-y-4">
                <p className="font-semibold text-sm text-[#0F172A]">Company</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">About LibertyMD</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Careers</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Medical Reviewers</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Team</li>
                </ul>
              </div>

              <div className="space-y-4">
                <p className="font-semibold text-sm text-[#0F172A]">Conditions</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">Respiratory Care</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Cardiovascular</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Neurology & Migraine</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">All Conditions</li>
                </ul>

                <p className="font-semibold text-sm text-[#0F172A] pt-4">Research</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">Clinical Blog</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Peer-Reviewed RAG</li>
                </ul>
              </div>

              <div className="space-y-4">
                <p className="font-semibold text-sm text-[#0F172A]">Partnerships</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">Become a Partner</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">EU Health Systems</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">US Insurance Network</li>
                </ul>
              </div>
            </div>

            {/* Right Side: CARIN / HIPAA / LegitScript Badges using real image URLs */}
            <div className="flex items-center gap-6 shrink-0 self-start">
              <img
                src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/carin-accredited.png"
                alt="CARIN Accredited Code of Conduct"
                className="h-16 w-auto object-contain hover:scale-105 transition-transform drop-shadow-sm"
              />
              <img
                src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/hipaa-certified.png"
                alt="HIPAA Certified"
                className="h-16 w-auto object-contain hover:scale-105 transition-transform drop-shadow-sm"
              />
              <img
                src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/legit_script.png"
                alt="LegitScript Certified"
                className="h-16 w-auto object-contain hover:scale-105 transition-transform drop-shadow-sm"
              />
            </div>
          </div>
        </div>

        {/* Center Patient Oath Emblem and pledge */}
        <div className="relative z-10 flex flex-col items-center justify-center px-6 py-12 text-center sm:px-10 sm:py-16">
          {/* Patient Oath Circle Seal Emblem */}
          <div className="hover:scale-105 transition-transform">
            <PatientOathEmblem className="w-48 h-48" />
          </div>

          <p className="libertymd-type-footer-oath mx-auto mt-10 max-w-4xl text-balance font-medium text-[#0F172A] sm:mt-12">
            I{' '}
            <strong className="font-extrabold">
              will first do no harm. Every response, every recommendation, and every action taken by LibertyMD will be measured against one question: does this serve the patient’s wellbeing?
            </strong>
          </p>
        </div>

        {/* Bottom Copyright */}
        <div className="relative z-10 max-w-7xl mx-auto px-6 sm:px-10 py-6 w-full flex flex-col sm:flex-row items-center justify-between text-xs text-[#475569] border-t border-[#CBD5E1]/60">
          <p>© {new Date().getFullYear()} LibertyMD Health Technologies. All rights reserved.</p>
          <p>Privacy-first AI triage • EU GDPR Article 9 & US HIPAA Safe Harbor</p>
        </div>
      </footer>
    </div>
  );
}
