import React, { useState, useEffect, useRef } from 'react';
import { 
  ShieldCheck, 
  Globe, 
  Send, 
  ArrowRight,
  UserCheck, 
  Sparkles, 
  Clock, 
  ArrowLeft, 
  HeartPulse, 
  FileText, 
  Video, 
  CheckCircle2, 
  AlertTriangle,
  Activity,
  Lock,
  ChevronRight,
  CheckCircle,
  Loader2,
  Mail,
  Menu,
  RotateCcw,
  Star,
  Stethoscope
} from 'lucide-react';
import { supabase } from '../../lib/supabaseClient';
import LibertyMDFooterRibbon from './LibertyMDFooterRibbon';
import { PatientOathEmblem } from './LibertyMDFooterBadges';
import LibertyMD3DBlobLogo from './LibertyMD3DBlobLogo';
import LibertyMDMedicalCrossLogo from './LibertyMDMedicalCrossLogo';
import LibertyMDHumanSilhouettes from './LibertyMDHumanSilhouettes';
import LibertyMDPremiumLogo from './LibertyMDPremiumLogo';
import LibertyMDParticleWaveSeparator from './LibertyMDParticleWaveSeparator';

interface LibertyMDAppProps {
  onBack?: () => void;
}

interface ChatMessage {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  options?: string[];
  kind?: 'normal' | 'system' | 'emergency' | 'report';
  triageData?: {
    severity: 'low' | 'moderate' | 'urgent';
    possibleCauses: string[];
    actionPlan: string[];
    redFlags: string[];
  };
}

type ChatPhase =
  | 'initial'
  | 'consent_required'
  | 'demographics_required'
  | 'intake'
  | 'report_ready'
  | 'emergency_end'
  | 'error';

interface LibertyReport {
  summary: string;
  differentials: Array<{
    name: string;
    confidence?: string;
    description?: string;
    reason?: string;
  }>;
  plan: string[];
  redFlags: string[];
  soap: {
    subjective: string;
    objective: string;
    assessment: string;
    plan: string;
  };
}

const asText = (value: unknown, fallback = '') => {
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) return value.filter(Boolean).join('\n');
  if (value && typeof value === 'object') return JSON.stringify(value, null, 2);
  return fallback;
};

const listFrom = (value: unknown): string[] => {
  if (!value) return [];
  if (Array.isArray(value)) {
    return value.map((item) => (typeof item === 'string' ? item : asText(item))).filter(Boolean);
  }
  if (typeof value === 'string') {
    return value.split(/\n|;|\.\s+/).map((item) => item.trim()).filter(Boolean);
  }
  return [];
};

const normalizeReport = (raw: any): LibertyReport => {
  const data = raw?.report || raw?.output || raw || {};
  const differentials = Array.isArray(data?.differential_diagnosis)
    ? data.differential_diagnosis
    : Array.isArray(data?.diagnoses)
      ? data.diagnoses
      : Array.isArray(data)
        ? data
        : [];
  const normalizedDifferentials = differentials.slice(0, 4).map((item: any) => ({
    name: item?.full_name || item?.name || item?.condition || item?.diagnosis || 'Clinical consideration',
    confidence: item?.confidence || item?.confidence_score || item?.likelihood,
    description: item?.description || item?.summary,
    reason: item?.reason || item?.rationale || item?.supporting_reason,
  }));
  const soap = data?.soap || data?.soap_note || data?.SOAP || {};
  return {
    summary: asText(
      data?.patient_summary || data?.summary || data?.share_report || data?.report_summary,
      'LibertyMD completed the AI Care intake and generated a doctor-ready report.'
    ),
    differentials: normalizedDifferentials,
    plan: listFrom(data?.plan || data?.care_plan || data?.assessment_plan || data?.recommendations).slice(0, 6),
    redFlags: listFrom(data?.red_flags || data?.warning_signs || data?.seek_care_if).slice(0, 6),
    soap: {
      subjective: asText(soap?.subjective || data?.subjective, 'Symptoms and history captured during chat.'),
      objective: asText(soap?.objective || data?.objective, 'No vitals or physical exam were directly measured in this AI consult.'),
      assessment: asText(soap?.assessment || data?.assessment || normalizedDifferentials.map((d) => d.name).join(', '), 'Assessment generated by the AI Care diagnosis workflow.'),
      plan: asText(soap?.plan || data?.plan || data?.care_plan, 'Follow the plan above and seek care urgently if red flags appear.'),
    },
  };
};

export default function LibertyMDApp({ onBack }: LibertyMDAppProps) {
  const [region, setRegion] = useState<'EU' | 'US'>('EU');
  const [input, setInput] = useState('');
  const [phase, setPhase] = useState<ChatPhase>('initial');
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [pendingSymptom, setPendingSymptom] = useState('');
  const [consent, setConsent] = useState({ terms: false, ai: false, emergency: false });
  const [demographics, setDemographics] = useState({ age: '', sex: '' });
  const [report, setReport] = useState<LibertyReport | null>(null);
  const [email, setEmail] = useState('');
  const [savedEmail, setSavedEmail] = useState('');
  const [error, setError] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: '1',
      sender: 'ai',
      kind: 'system',
      text: `Tell me what is happening, when it started, and what worries you most. I'll ask a few focused questions and flag urgent warning signs.`
    }
  ]);
  const [isTyping, setIsTyping] = useState(false);
  const [selectedTab, setSelectedTab] = useState<'chat' | 'doctors'>('chat');
  const [scrollY, setScrollY] = useState(0);
  const messagesEndRef = useRef<HTMLDivElement | null>(null);
  const chatPanelRef = useRef<HTMLDivElement | null>(null);
  const logoDockHeadlineRef = useRef<HTMLHeadingElement | null>(null);
  const heroSymptomsRef = useRef<HTMLTextAreaElement | null>(null);
  const hasActiveConsultRef = useRef(false);
  const consentReady = consent.terms && consent.ai && consent.emergency;
  const demographicsReady = demographics.age.trim() && demographics.sex;

  useEffect(() => {
    const handleScroll = () => setScrollY(window.scrollY);
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    if (!hasActiveConsultRef.current) return;
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  }, [messages, isTyping, report]);

  const SAMPLE_CASES = [
    {
      label: 'Sharp lower right abdominal pain & mild fever',
      symptom: 'I have sharp pain in my lower right abdomen that started 6 hours ago near my belly button, with nausea and low fever.',
      response: {
        text: 'Based on your presentation of acute right lower quadrant (RLQ) abdominal pain originating periumbilically with associated nausea and low-grade pyrexia, acute appendicitis is a primary clinical differential that must be urgently evaluated.',
        triageData: {
          severity: 'urgent' as const,
          possibleCauses: [
            'Acute Appendicitis (McBurney point tenderness)',
            'Mesenteric Lymphadenitis',
            'Right-sided Renal Colic / Nephrolithiasis'
          ],
          actionPlan: [
            'Seek immediate evaluation at an Urgent Care or Emergency Department.',
            'Do not consume solid foods or analgesics that mask peritoneal signs prior to surgical consult.',
            'Connect with a LibertyMD physician below for an instant priority referral.'
          ],
          redFlags: [
            'Rebound tenderness or rigid abdomen',
            'Temperature exceeding 38.5°C (101.3°F)',
            'Inability to stand upright or walk without severe guarding'
          ]
        }
      }
    },
    {
      label: 'Persistent 3-day migraine & photophobia',
      symptom: 'I have had a throbbing unilateral headache on my left temple for 3 days with sensitivity to bright lights and nausea.',
      response: {
        text: 'Your symptoms align closely with Acute Migraine with Photophobia. Because symptoms have persisted for 72 hours (Status Migrainosus risk), targeted abortive therapy or a clinical evaluation is recommended.',
        triageData: {
          severity: 'moderate' as const,
          possibleCauses: [
            'Migraine Headache without Aura',
            'Tension-type Headache with nausea overlay',
            'Cervicogenic Headache'
          ],
          actionPlan: [
            'Rest in a dark, quiet room and maintain hydration with electrolytes.',
            'Consider NSAIDs or Triptans if previously prescribed by your doctor.',
            'Book a €39 / $39 LibertyMD video consultation for immediate prescription refill or rescue medication.'
          ],
          redFlags: [
            'Sudden thunderclap onset reaching maximum intensity within 60 seconds',
            'Associated limb weakness, slurred speech, or vision loss',
            'Headache following recent head trauma'
          ]
        }
      }
    },
    {
      label: 'Mild dry cough & scratchy throat',
      symptom: 'I have had a mild dry cough and a scratchy throat for 2 days. No high fever or shortness of breath.',
      response: {
        text: 'This presentation is most consistent with an uncomplicated Viral Upper Respiratory Tract Infection (Common Cold or early Pharyngitis).',
        triageData: {
          severity: 'low' as const,
          possibleCauses: [
            'Viral Upper Respiratory Infection (URI)',
            'Seasonal Allergic Rhinitis / Post-nasal drip',
            'Mild Acute Pharyngitis'
          ],
          actionPlan: [
            'Supportive care: warm salt-water gargles, honey tea, and adequate rest.',
            'Monitor for secondary bacterial symptoms over the next 48-72 hours.',
            'Request a digital doctor note for work/university if needed.'
          ],
          redFlags: [
            'Difficulty breathing or wheezing at rest',
            'Fever > 39°C persisting beyond 3 days',
            'Inability to swallow fluids due to severe throat swelling'
          ]
        }
      }
    }
  ];

  const invokeCareProxy = async (body: Record<string, unknown>) => {
    const { data, error: fnError } = await supabase.functions.invoke('ai-care-proxy', {
      body: {
        product: 'libertymd',
        anonymous: true,
        region,
        demographics,
        ...body
      }
    });
    if (fnError) throw fnError;
    return data;
  };

  const startSessionIfNeeded = async () => {
    if (sessionId) return sessionId;
    const data = await invokeCareProxy({ action: 'start_session' });
    if (!data?.session_id) throw new Error('Unable to start LibertyMD session.');
    setSessionId(data.session_id);
    if (data.initial_question) {
      setMessages(prev => [...prev, {
        id: `${Date.now()}-initial`,
        sender: 'ai',
        kind: 'system',
        text: data.initial_question,
        options: Array.isArray(data.options) ? data.options : [],
      }]);
    }
    return data.session_id as string;
  };

  const sendToWorkflow = async (text: string, activeSessionId?: string) => {
    const sid = activeSessionId || sessionId;
    if (!sid) return;
    setIsTyping(true);
    setError('');
    try {
      const data = await invokeCareProxy({
        action: 'send_message',
        session_id: sid,
        message: text,
        stream: false,
      });

      if (data?.emergency) {
        setPhase('emergency_end');
        setMessages(prev => [...prev, {
          id: `${Date.now()}-emergency`,
          sender: 'ai',
          kind: 'emergency',
          text: data.message || 'These symptoms may be an emergency. Call emergency services or go to the ER now.',
        }]);
        return;
      }

      if (data?.diagnosis_ready || data?.report) {
        const nextReport = normalizeReport(data.report || data);
        setReport(nextReport);
        setPhase('report_ready');
        setMessages(prev => [...prev, {
          id: `${Date.now()}-report`,
          sender: 'ai',
          kind: 'report',
          text: 'Your LibertyMD report is ready. Review the care plan, red flags, and SOAP note below.',
        }]);
        return;
      }

      setPhase('intake');
      setMessages(prev => [...prev, {
        id: `${Date.now()}-ai`,
        sender: 'ai',
        text: data?.next_question || 'Could you tell me more about that?',
        options: Array.isArray(data?.options) ? data.options : [],
      }]);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'The LibertyMD AI Care workflow is temporarily unavailable.';
      setError(message);
      setPhase('error');
      setMessages(prev => [...prev, {
        id: `${Date.now()}-error`,
        sender: 'ai',
        kind: 'system',
        text: 'I could not reach the AI Care workflow. Please try again in a moment.',
      }]);
    } finally {
      setIsTyping(false);
    }
  };

  const continueAfterGates = async (symptom = pendingSymptom) => {
    if (!symptom.trim()) return;
    setPhase('intake');
    chatPanelRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    try {
      const sid = await startSessionIfNeeded();
      await sendToWorkflow(symptom, sid);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'The LibertyMD AI Care workflow is temporarily unavailable.';
      setError(message);
      setPhase('error');
      setIsTyping(false);
      setMessages(prev => [...prev, {
        id: `${Date.now()}-startup-error`,
        sender: 'ai',
        kind: 'system',
        text: 'I could not start the AI Care workflow. Please try again in a moment.',
      }]);
    }
  };

  const handleSend = (textToSend?: string) => {
    const text = (textToSend || input).trim();
    if (!text || isTyping || phase === 'emergency_end' || phase === 'report_ready') return;

    hasActiveConsultRef.current = true;
    setPendingSymptom(text);
    setInput('');
    setReport(null);
    setSavedEmail('');
    setMessages(prev => [...prev, {
      id: Date.now().toString(),
      sender: 'user',
      text
    }]);
    chatPanelRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });

    if (!consentReady) {
      setPhase('consent_required');
      return;
    }
    if (!demographicsReady) {
      setPhase('demographics_required');
      return;
    }
    void continueAfterGates(text);
  };

  const resetConsult = () => {
    hasActiveConsultRef.current = false;
    setInput('');
    setPhase('initial');
    setSessionId(null);
    setPendingSymptom('');
    setReport(null);
    setSavedEmail('');
    setEmail('');
    setError('');
    setMessages([
      {
        id: '1',
        sender: 'ai',
        kind: 'system',
        text: `Tell me what is happening, when it started, and what worries you most. I'll ask a few focused questions and flag urgent warning signs.`
      }
    ]);
  };

  const dockZoneRef = useRef<HTMLDivElement | null>(null);
  const activeOptions = messages[messages.length - 1]?.options || [];
  const pathwaySteps = [
    ['01', 'Share what is happening', 'Start with symptoms, timeline, medications, and what worries you most.'],
    ['02', 'Safety screen', 'AI Care guardrails check for urgent warning signs before normal intake continues.'],
    ['03', 'Focused follow-up', 'The workflow asks concise questions until it has enough context for a report.'],
    ['04', 'Doctor-ready report', 'LibertyMD creates a summary, care plan, red flags, and SOAP note for handoff.']
  ];

  return (
    <div
      className="min-h-screen text-[#111827] font-sans selection:bg-[#2563EB] selection:text-white"
      style={{
        background:
          'linear-gradient(180deg, #FBFCF9 0%, #F5F9FF 34%, #F3F8F2 66%, #EFF6FF 100%)',
      }}
    >
      <main>
        <section className="relative z-10 flex min-h-[100svh] flex-col overflow-visible px-5 sm:px-8">
          <div className="absolute inset-0 -z-10 bg-[linear-gradient(180deg,rgba(255,255,255,0.94)_0%,rgba(247,250,255,0.9)_54%,rgba(240,248,243,0.96)_100%)]" />

          <header className="mx-auto flex h-16 w-full max-w-7xl shrink-0 items-center justify-between">
            <a
              href="/liberty-md"
              aria-label="LibertyMD home"
              className="font-serif text-xl font-semibold text-[#111827] transition-colors hover:text-[#2563EB] sm:text-2xl"
            >
              LibertyMD
            </a>

            <div className="flex items-center gap-4 text-sm font-semibold text-[#334155] sm:gap-6">
              <div aria-label="Care region" className="hidden items-center gap-2 text-xs text-[#64748B] sm:flex">
                {(['EU', 'US'] as const).map((item) => (
                  <button
                    key={item}
                    type="button"
                    onClick={() => setRegion(item)}
                    aria-pressed={region === item}
                    className={`border-b py-1 transition-colors ${
                      region === item
                        ? 'border-[#2563EB] text-[#2563EB]'
                        : 'border-transparent hover:text-[#111827]'
                    }`}
                  >
                    {item}
                  </button>
                ))}
              </div>
              <a href="/login" className="transition-colors hover:text-[#2563EB]">Log in</a>
              <a href="/login?mode=signup" className="hidden transition-colors hover:text-[#2563EB] sm:inline">Sign up</a>
              <button
                type="button"
                aria-label="View how LibertyMD works"
                onClick={() => chatPanelRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })}
                className="inline-flex h-9 w-9 items-center justify-center text-[#111827] transition-colors hover:text-[#2563EB]"
              >
                <Menu className="h-5 w-5" />
              </button>
            </div>
          </header>

          <div className="mx-auto flex w-full max-w-7xl flex-1 flex-col items-center justify-center pb-8 text-center sm:pb-0 [@media(max-height:700px)]:pb-0">
            <style>
              {`
                @keyframes libertymd-tagline-step-1 {
                  0% { opacity: 0; transform: translateY(9px); filter: blur(3px); }
                  8%, 78% { opacity: 1; transform: translateY(0); filter: blur(0); }
                  88%, 100% { opacity: 0; transform: translateY(-5px); filter: blur(2px); }
                }

                @keyframes libertymd-tagline-step-2 {
                  0%, 14% { opacity: 0; transform: translateY(9px); filter: blur(3px); }
                  22%, 78% { opacity: 1; transform: translateY(0); filter: blur(0); }
                  88%, 100% { opacity: 0; transform: translateY(-5px); filter: blur(2px); }
                }

                @keyframes libertymd-tagline-step-3 {
                  0%, 29% { opacity: 0; transform: translateY(9px); filter: blur(3px); }
                  37%, 78% { opacity: 1; transform: translateY(0); filter: blur(0); }
                  88%, 100% { opacity: 0; transform: translateY(-5px); filter: blur(2px); }
                }

                .libertymd-start-chat-cta {
                  box-shadow:
                    inset 0 1px 0 rgba(255, 255, 255, 0.44),
                    inset 0 -1px 0 rgba(15, 54, 153, 0.28),
                    0 11px 26px rgba(37, 99, 235, 0.34);
                  transform: translateY(0);
                }

                .libertymd-start-chat-cta::before {
                  content: '';
                  position: absolute;
                  top: -35%;
                  bottom: -35%;
                  left: -42%;
                  width: 24%;
                  background: linear-gradient(
                    105deg,
                    rgba(255, 255, 255, 0) 0%,
                    rgba(255, 255, 255, 0.16) 30%,
                    rgba(255, 255, 255, 0.62) 50%,
                    rgba(255, 255, 255, 0.16) 70%,
                    rgba(255, 255, 255, 0) 100%
                  );
                  filter: blur(1px);
                  pointer-events: none;
                  transform: translateX(-180%) skewX(-16deg);
                  will-change: transform;
                }

                @keyframes libertymd-start-chat-satin-shine {
                  0% { transform: translateX(-180%) skewX(-16deg); }
                  18% { transform: translateX(700%) skewX(-16deg); }
                  100% { transform: translateX(700%) skewX(-16deg); }
                }

                @keyframes libertymd-start-chat-hover-shine {
                  from { transform: translateX(-180%) skewX(-16deg); }
                  to { transform: translateX(700%) skewX(-16deg); }
                }

                .libertymd-start-chat-cta--waiting::before {
                  animation: libertymd-start-chat-satin-shine 9.6s cubic-bezier(0.4, 0, 0.2, 1) 1.2s infinite;
                }

                .libertymd-start-chat-cta:hover {
                  background-color: #1D5FE2;
                  box-shadow:
                    inset 0 1px 0 rgba(255, 255, 255, 0.5),
                    inset 0 -1px 0 rgba(15, 54, 153, 0.3),
                    0 13px 30px rgba(37, 99, 235, 0.4);
                }

                .libertymd-start-chat-cta:hover::before {
                  animation: libertymd-start-chat-hover-shine 1.45s cubic-bezier(0.4, 0, 0.2, 1) 1;
                }

                .libertymd-start-chat-cta:active {
                  transform: translateY(1px) scale(0.99);
                  box-shadow:
                    inset 0 1px 0 rgba(255, 255, 255, 0.34),
                    inset 0 -1px 0 rgba(15, 54, 153, 0.34),
                    0 7px 18px rgba(37, 99, 235, 0.3);
                }

                .libertymd-start-chat-arrow {
                  transition: transform 220ms cubic-bezier(0.22, 1, 0.36, 1);
                }

                .libertymd-start-chat-cta:hover .libertymd-start-chat-arrow {
                  transform: translateX(3px);
                }

                @media (prefers-reduced-motion: reduce) {
                  .libertymd-tagline-word {
                    animation: none !important;
                    opacity: 1 !important;
                    transform: none !important;
                    filter: none !important;
                  }

                  .libertymd-start-chat-cta,
                  .libertymd-start-chat-cta::before,
                  .libertymd-start-chat-arrow {
                    animation: none !important;
                    transform: none !important;
                  }
                }
              `}
            </style>

            <h1 className="font-serif text-6xl font-semibold leading-none text-[#111827] sm:text-7xl [@media(max-height:700px)]:whitespace-nowrap [@media(max-height:700px)]:text-5xl">
              LibertyMD
            </h1>
            <p
              className="mt-4 flex min-h-7 flex-wrap items-center justify-center gap-x-2 text-sm font-bold text-[#17325F] sm:mt-2 sm:gap-x-3 sm:text-lg [@media(max-height:700px)]:mt-2 [@media(max-height:700px)]:text-xs"
              aria-label="Free, Anonymous, Built by Doctors"
            >
              {['Free', 'Anonymous', 'Built by Doctors'].map((phrase, index) => (
                <React.Fragment key={phrase}>
                  {index > 0 && (
                    <span
                      aria-hidden="true"
                      className="libertymd-tagline-word opacity-0"
                      style={{
                        animation: `libertymd-tagline-step-${index + 1} 5.4s ease-in-out infinite`,
                        willChange: 'opacity, transform, filter',
                      }}
                    >
                      •
                    </span>
                  )}
                  <span
                    className="libertymd-tagline-word opacity-0"
                    style={{
                      animation: `libertymd-tagline-step-${index + 1} 5.4s ease-in-out infinite`,
                      willChange: 'opacity, transform, filter',
                    }}
                  >
                    {phrase}
                  </span>
                </React.Fragment>
              ))}
            </p>

            <LibertyMDPremiumLogo
              scrollY={phase === 'initial' ? scrollY : 0}
              dockHeadlineRef={logoDockHeadlineRef}
              className="z-10 mt-[var(--libertymd-gap-tagline-logo)] mb-[var(--libertymd-gap-pedestal-input)] [@media(max-height:700px)]:-mt-2 [@media(max-height:700px)]:mb-2"
            />

            <div className="relative z-20 w-full max-w-5xl">
              <form
                onSubmit={(event) => {
                  event.preventDefault();
                  if (!input.trim()) {
                    heroSymptomsRef.current?.focus();
                    return;
                  }
                  handleSend();
                }}
                className="relative min-h-[205px] w-full rounded-[22px] border border-white/80 bg-white/75 p-6 pt-8 text-left shadow-[0_18px_60px_rgba(15,23,42,0.08)] backdrop-blur-[2px] sm:min-h-[238px] sm:p-8 sm:pt-9 lg:min-h-[240px] [@media(max-height:700px)]:min-h-[160px] [@media(max-height:700px)]:p-4 [@media(max-height:700px)]:pt-7"
              >
                <label
                  htmlFor="libertymd-hero-symptoms"
                  className="absolute -top-5 left-6 rounded-t-[28px] rounded-br-[28px] bg-[#E5FFB8] px-5 py-3 text-base font-black text-[#111827] sm:left-10 sm:px-7 sm:text-xl [@media(max-height:700px)]:-top-4 [@media(max-height:700px)]:left-6 [@media(max-height:700px)]:px-5 [@media(max-height:700px)]:py-2 [@media(max-height:700px)]:text-sm"
                >
                  What brings you in?
                </label>
                <textarea
                  ref={heroSymptomsRef}
                  id="libertymd-hero-symptoms"
                  aria-label="Describe your symptoms or ask a health question"
                  rows={3}
                  value={input}
                  onChange={(event) => setInput(event.target.value)}
                  onKeyDown={(event) => {
                    if (event.key === 'Enter' && !event.shiftKey) {
                      event.preventDefault();
                      handleSend();
                    }
                  }}
                  placeholder="Describe symptom or ask any health questions..."
                  className="min-h-[88px] w-full resize-none bg-transparent text-base leading-7 text-[#334155] outline-none placeholder:text-[#5B5B5B] sm:min-h-[120px] sm:text-xl [@media(max-height:700px)]:min-h-[54px] [@media(max-height:700px)]:text-sm [@media(max-height:700px)]:leading-6"
                />
                <button
                  type="submit"
                  aria-label={input.trim() ? 'Start LibertyMD chat' : 'Start by describing your symptoms'}
                  className={`libertymd-start-chat-cta ${!input.trim() ? 'libertymd-start-chat-cta--waiting' : ''} absolute bottom-6 left-6 right-6 isolate inline-flex h-14 cursor-pointer items-center justify-center gap-3 overflow-hidden rounded-full bg-[#2563EB] px-8 text-base font-bold text-white ring-1 ring-white/60 transition-[background-color,box-shadow,transform] duration-200 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#93C5FD] sm:bottom-8 sm:left-auto sm:right-8 sm:w-64 [@media(max-height:700px)]:bottom-4 [@media(max-height:700px)]:left-4 [@media(max-height:700px)]:right-4 [@media(max-height:700px)]:h-12 [@media(max-height:700px)]:w-auto`}
                >
                  <span className="relative z-10">Start chat</span>
                  <ArrowRight className="libertymd-start-chat-arrow relative z-10 h-5 w-5" />
                </button>
              </form>

              <div className="mt-5 flex flex-row items-center justify-between gap-3 text-xs font-medium text-[#626262] sm:mt-2 sm:text-sm [@media(max-height:700px)]:mt-0 [@media(max-height:700px)]:gap-1">
                <div className="flex flex-nowrap items-center justify-start gap-2 [@media(max-height:700px)]:gap-1">
                  <span>4.7</span>
                  <span className="inline-flex gap-0.5" aria-label="4.7 out of 5 rating">
                    {[0, 1, 2, 3, 4].map((item) => (
                      <span key={item} className="inline-flex h-5 w-5 items-center justify-center bg-[#169B52] [@media(max-height:700px)]:h-4 [@media(max-height:700px)]:w-4">
                        <Star className="h-3.5 w-3.5 fill-white text-white [@media(max-height:700px)]:h-3 [@media(max-height:700px)]:w-3" />
                      </span>
                    ))}
                  </span>
                </div>
                <span className="inline-flex shrink-0 items-center gap-2 whitespace-nowrap">
                  <ShieldCheck className="h-5 w-5 text-[#626262]" />
                  HIPAA Compliant &amp; Private
                </span>
              </div>
            </div>
          </div>

          <LibertyMDParticleWaveSeparator className="opacity-[0.22] sm:opacity-[0.34]" />
        </section>

        <section ref={chatPanelRef} className="relative z-0 bg-[linear-gradient(180deg,rgba(245,250,243,0.96),rgba(237,247,241,0.98))] px-5 pb-16 pt-[300px] sm:px-8 sm:pt-[340px]">
          <div className="mx-auto max-w-3xl text-center">
            <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">From symptom to next step</p>
            <h2 ref={logoDockHeadlineRef} className="mt-3 text-4xl font-black leading-tight tracking-normal text-[#111827] sm:text-5xl">
              How LibertyMD works
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-[#5B6472] sm:text-base">
              Describe what you feel. LibertyMD checks urgent warning signs, asks focused questions, and prepares a report you can share with a doctor.
            </p>
          </div>

          <div className="mx-auto mt-14 grid max-w-6xl gap-12 text-left lg:grid-cols-[0.78fr_1.22fr] lg:items-start">
            <div className="lg:sticky lg:top-24">
              <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">Start a consultation</p>
              <h2 className="mt-3 max-w-sm text-3xl font-black leading-tight tracking-normal text-[#111827] sm:text-4xl">
                Begin in your own words.
              </h2>
              <p className="mt-4 max-w-sm text-sm leading-7 text-[#5B6472]">
                A sentence is enough. LibertyMD will ask only the questions needed to understand timing, severity, and safety.
              </p>

              <div className="mt-8 space-y-3">
                <p className="text-xs font-bold uppercase tracking-normal text-[#64748B]">Or try an example</p>
                {SAMPLE_CASES.map((item) => (
                  <button
                    key={item.label}
                    onClick={() => handleSend(item.symptom)}
                    className="block w-full border-t border-[#DDE7D8] py-3 text-left text-sm font-medium leading-6 text-[#334155] transition hover:text-[#2563EB]"
                  >
                    {item.label}
                  </button>
                ))}
              </div>

              <div className="mt-7 flex max-w-sm items-start gap-3 border-t border-[#DDE7D8] pt-5 text-xs leading-6 text-[#64748B]">
                <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-[#B45309]" />
                <p>For severe chest pain, trouble breathing, fainting, or other dangerous symptoms, call emergency services now.</p>
              </div>
            </div>

            <div className="min-h-[560px]">
              <div className="mb-4 flex items-center justify-between border-b border-[#DDE7D8] pb-3">
                <div className="flex items-center gap-2.5">
                  <span className="h-2.5 w-2.5 rounded-full bg-[#16A34A]" />
                  <span className="text-sm font-bold text-[#111827]">LibertyMD care assistant</span>
                  <span className="hidden text-xs text-[#64748B] sm:inline">Private session · {region}</span>
                </div>
                <button onClick={resetConsult} className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#64748B] hover:text-[#2563EB]">
                  <RotateCcw className="h-3.5 w-3.5" />
                  Reset
                </button>
              </div>

              <div className="space-y-5">
                {messages.map((message) => (
                  <div key={message.id} className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                    <div
                      className={`max-w-[88%] rounded-[20px] px-5 py-4 text-sm leading-7 shadow-[0_14px_40px_rgba(15,23,42,0.045)] ${
                        message.sender === 'user'
                          ? 'bg-[#5661F6] text-white'
                          : message.kind === 'emergency'
                          ? 'bg-[#FFF1F2] text-[#991B1B]'
                          : message.kind === 'report'
                          ? 'bg-white text-[#166534]'
                          : 'bg-white text-[#334155]'
                      }`}
                    >
                      {message.text}
                    </div>
                  </div>
                ))}

                {phase === 'consent_required' && (
                  <div className="border-t border-[#DDE7D8] pt-6">
                    <h3 className="text-lg font-black text-[#111827]">Before we continue</h3>
                    <p className="mt-2 max-w-2xl text-sm leading-7 text-[#5B6472]">
                      LibertyMD is an AI care assistant, not a replacement for emergency services or a licensed clinician.
                    </p>
                    <div className="mt-5 space-y-3">
                      {[
                        ['terms', 'I accept the LibertyMD terms for this AI consult.'],
                        ['ai', 'I understand this is AI guidance, not a formal diagnosis.'],
                        ['emergency', 'I will call emergency services for severe or dangerous symptoms.']
                      ].map(([key, label]) => (
                        <label key={key} className="flex items-start gap-3 text-sm leading-6 text-[#334155]">
                          <input
                            type="checkbox"
                            checked={consent[key as keyof typeof consent]}
                            onChange={(event) => setConsent(prev => ({ ...prev, [key]: event.target.checked }))}
                            className="mt-1 h-4 w-4 rounded border-[#CBD5E1] text-[#5661F6]"
                          />
                          <span>{label}</span>
                        </label>
                      ))}
                    </div>
                    <button
                      type="button"
                      disabled={!consentReady}
                      onClick={() => setPhase('demographics_required')}
                      className="mt-5 rounded-full bg-[#5661F6] px-5 py-2.5 text-sm font-bold text-white transition hover:bg-[#4651E6] disabled:cursor-not-allowed disabled:opacity-40"
                    >
                      Continue
                    </button>
                  </div>
                )}

                {phase === 'demographics_required' && (
                  <form
                    onSubmit={(event) => {
                      event.preventDefault();
                      if (demographicsReady) void continueAfterGates();
                    }}
                    className="border-t border-[#DDE7D8] pt-6"
                  >
                    <h3 className="text-lg font-black text-[#111827]">Basic clinical context</h3>
                    <p className="mt-2 max-w-2xl text-sm leading-7 text-[#5B6472]">
                      Age and biological sex help the AI Care workflow ask safer follow-up questions.
                    </p>
                    <div className="mt-5 grid gap-4 sm:grid-cols-2">
                      <label className="grid gap-2 text-xs font-bold uppercase tracking-normal text-[#64748B]">
                        Age
                        <input
                          inputMode="numeric"
                          value={demographics.age}
                          onChange={(event) => setDemographics(prev => ({ ...prev, age: event.target.value }))}
                          placeholder="34"
                          className="border-b border-[#BFD2B7] bg-transparent py-3 text-base font-semibold normal-case tracking-normal text-[#111827] outline-none focus:border-[#5661F6]"
                        />
                      </label>
                      <label className="grid gap-2 text-xs font-bold uppercase tracking-normal text-[#64748B]">
                        Biological sex
                        <select
                          value={demographics.sex}
                          onChange={(event) => setDemographics(prev => ({ ...prev, sex: event.target.value }))}
                          className="border-b border-[#BFD2B7] bg-transparent py-3 text-base font-semibold normal-case tracking-normal text-[#111827] outline-none focus:border-[#5661F6]"
                        >
                          <option value="">Select</option>
                          <option value="female">Female</option>
                          <option value="male">Male</option>
                          <option value="intersex">Intersex</option>
                          <option value="prefer_not_to_say">Prefer not to say</option>
                        </select>
                      </label>
                    </div>
                    <button
                      disabled={!demographicsReady || isTyping}
                      className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#5661F6] px-5 py-2.5 text-sm font-bold text-white transition hover:bg-[#4651E6] disabled:cursor-not-allowed disabled:opacity-40"
                    >
                      {isTyping && <Loader2 className="h-4 w-4 animate-spin" />}
                      Start intake
                    </button>
                  </form>
                )}

                {error && (
                  <div className="border-t border-[#FDE68A] pt-5 text-sm leading-6 text-[#92400E]">
                    {error}
                  </div>
                )}

                {isTyping && (
                  <div className="flex items-center gap-2 text-sm text-[#64748B]">
                    <Loader2 className="h-4 w-4 animate-spin text-[#5661F6]" />
                    Checking safety and generating the next clinical step...
                  </div>
                )}

                {report && (
                  <div className="border-t border-[#DDE7D8] pt-7">
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                      <div>
                        <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">Share LibertyMD Report</p>
                        <h3 className="mt-2 text-3xl font-black tracking-normal text-[#111827]">Assessment & Plan</h3>
                      </div>
                      <button
                        type="button"
                        onClick={() => setSelectedTab('doctors')}
                        className="w-max rounded-full bg-[#111827] px-5 py-2.5 text-sm font-bold text-white hover:bg-[#1F2937]"
                      >
                        Continue to a licensed doctor
                      </button>
                    </div>

                    <p className="mt-5 max-w-3xl text-base leading-8 text-[#334155]">{report.summary}</p>

                    {report.differentials.length > 0 && (
                      <div className="mt-8 space-y-5 border-t border-[#DDE7D8] pt-6">
                        <p className="text-xs font-bold uppercase tracking-normal text-[#64748B]">Clinical considerations</p>
                        {report.differentials.map((item, index) => (
                          <div key={`${item.name}-${index}`} className="border-b border-[#DDE7D8] pb-5">
                            <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                              <div>
                                <h4 className="font-bold text-[#111827]">{item.name}</h4>
                                {item.description && <p className="mt-1 text-sm leading-7 text-[#5B6472]">{item.description}</p>}
                                {item.reason && <p className="mt-2 text-xs leading-6 text-[#64748B]">{item.reason}</p>}
                              </div>
                              {item.confidence && <span className="text-xs font-bold text-[#2563EB]">{item.confidence}</span>}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    <div className="mt-8 grid gap-8 md:grid-cols-2">
                      <div>
                        <h4 className="text-sm font-black text-[#166534]">Care Plan</h4>
                        <ul className="mt-3 space-y-2 text-sm leading-7 text-[#334155]">
                          {(report.plan.length ? report.plan : ['Monitor symptoms, rest, hydrate, and follow up if symptoms worsen.']).map((item, index) => (
                            <li key={index}>- {item}</li>
                          ))}
                        </ul>
                      </div>
                      <div>
                        <h4 className="text-sm font-black text-[#991B1B]">Red Flags</h4>
                        <ul className="mt-3 space-y-2 text-sm leading-7 text-[#334155]">
                          {(report.redFlags.length ? report.redFlags : ['Seek urgent care for chest pain, trouble breathing, confusion, fainting, severe worsening pain, or symptoms that feel dangerous.']).map((item, index) => (
                            <li key={index}>- {item}</li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    <div className="mt-8 border-t border-[#DDE7D8] pt-6">
                      <h4 className="font-black text-[#111827]">SOAP Note</h4>
                      <div className="mt-4 grid gap-x-8 gap-y-5 md:grid-cols-2">
                        {[
                          ['Subjective', report.soap.subjective],
                          ['Objective', report.soap.objective],
                          ['Assessment', report.soap.assessment],
                          ['Plan', report.soap.plan]
                        ].map(([label, value]) => (
                          <div key={label}>
                            <p className="text-xs font-bold uppercase tracking-normal text-[#64748B]">{label}</p>
                            <p className="mt-2 whitespace-pre-line text-sm leading-7 text-[#334155]">{value}</p>
                          </div>
                        ))}
                      </div>
                    </div>

                    <form
                      onSubmit={(event) => {
                        event.preventDefault();
                        if (!email.trim()) return;
                        setSavedEmail(email.trim());
                        setEmail('');
                      }}
                      className="mt-8 flex flex-col gap-3 border-t border-[#DDE7D8] pt-5 sm:flex-row sm:items-center"
                    >
                      <span className="text-sm text-[#5B6472] sm:flex-1">
                        {savedEmail ? `Report saved for ${savedEmail}` : 'Email this report or use it for doctor handoff.'}
                      </span>
                      {!savedEmail && (
                        <>
                          <input
                            type="email"
                            value={email}
                            onChange={(event) => setEmail(event.target.value)}
                            placeholder="you@example.com"
                            className="border-b border-[#BFD2B7] bg-transparent px-1 py-2 text-sm outline-none focus:border-[#5661F6]"
                          />
                          <button className="rounded-full bg-[#111827] px-5 py-2 text-sm font-bold text-white">Save</button>
                        </>
                      )}
                    </form>
                  </div>
                )}

                <div ref={messagesEndRef} />
              </div>

              <div className="mt-6 border-t border-[#DDE7D8] pt-4">
                {phase !== 'emergency_end' && phase !== 'report_ready' && activeOptions.length > 0 && (
                  <div className="mb-4 flex flex-wrap gap-x-4 gap-y-2">
                    {activeOptions.map((option) => (
                      <button
                        key={option}
                        type="button"
                        disabled={isTyping}
                        onClick={() => handleSend(option)}
                        className="text-left text-xs font-semibold leading-5 text-[#2563EB] hover:text-[#111827] disabled:opacity-50"
                      >
                        {option}
                      </button>
                    ))}
                  </div>
                )}

                <form
                  onSubmit={(event) => {
                    event.preventDefault();
                    handleSend();
                  }}
                  className="flex items-center gap-2 rounded-full border border-white bg-white/92 px-4 py-3 shadow-[0_16px_50px_rgba(37,99,235,0.07)] backdrop-blur-xl"
                >
                  <input
                    type="text"
                    value={input}
                    onChange={(event) => setInput(event.target.value)}
                    disabled={isTyping || phase === 'emergency_end' || phase === 'report_ready'}
                    placeholder={phase === 'report_ready' ? 'Report is ready above' : 'Answer the follow-up question...'}
                    className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#94A3B8]"
                  />
                  <button
                    type="submit"
                    aria-label="Send message"
                    disabled={!input.trim() || isTyping || phase === 'emergency_end' || phase === 'report_ready'}
                    className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#5661F6] text-white hover:bg-[#4651E6] disabled:cursor-not-allowed disabled:opacity-40"
                  >
                    <Send className="h-4 w-4" />
                  </button>
                </form>
              </div>
            </div>
          </div>
        </section>

        {selectedTab === 'doctors' && (
          <section className="border-t border-[#E6EDE3] bg-[linear-gradient(180deg,rgba(251,252,248,0.98),rgba(239,246,255,0.72))] px-5 py-16 sm:px-8">
            <div className="mx-auto max-w-6xl">
              <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">Licensed handoff</p>
              <h2 className="mt-3 max-w-xl text-3xl font-black tracking-normal text-[#111827] sm:text-4xl">
                Continue with a doctor when you need one.
              </h2>
              <div className="mt-10 grid gap-8 md:grid-cols-3">
                {[
                  ['Dr. Elena Rostova, MD', 'Urgent Care', '9 mins'],
                  ['Dr. Rajiv Patel, MD', 'Internal Medicine', '14 mins'],
                  ['Dr. Barry Pevner, MD', 'Family Medicine', '18 mins']
                ].map(([name, specialty, wait]) => (
                  <div key={name} className="border-t border-[#DDE7D8] pt-5">
                    <p className="text-xs font-bold uppercase tracking-normal text-[#64748B]">Available in {wait}</p>
                    <h3 className="mt-3 text-lg font-black text-[#111827]">{name}</h3>
                    <p className="mt-1 text-sm font-semibold text-[#2563EB]">{specialty}</p>
                    <p className="mt-3 text-sm leading-7 text-[#5B6472]">
                      Can review the AI report and advise next steps for {region === 'EU' ? '€39' : '$39'}.
                    </p>
                    <button className="mt-4 rounded-full bg-[#5661F6] px-5 py-2.5 text-sm font-bold text-white hover:bg-[#4651E6]">
                      Start visit
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </section>
        )}

        {/* Ambient Clinical Care Film — calm full-width band. Video edges are feathered and a soft
            glow sits behind so it melts into the surrounding sections instead of reading as a hard rectangle. */}
        <section className="relative overflow-hidden border-t border-[#E6EDE3] bg-[linear-gradient(180deg,rgba(245,250,243,0.96)_0%,rgba(248,250,247,0.97)_100%)] px-5 py-16 sm:px-8 sm:py-20">
          <div className="mx-auto max-w-3xl text-center">
            <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">Human care</p>
            <h2 className="mx-auto mt-3 max-w-xl text-3xl font-black tracking-normal text-[#111827] sm:text-4xl">
              A doctor&rsquo;s attention, built in.
            </h2>
            <p className="mx-auto mt-4 max-w-lg text-sm leading-7 text-[#5B6472]">
              Every triage is designed to hand off cleanly to a licensed physician.
            </p>
          </div>
          <div className="relative mx-auto mt-10 max-w-5xl">
            {/* Soft blue/peach glow matching the film's palette so the seams disappear */}
            <div
              aria-hidden="true"
              className="pointer-events-none absolute -inset-x-6 -inset-y-8 -z-0 bg-[radial-gradient(60%_60%_at_50%_50%,rgba(191,219,254,0.45),rgba(254,226,226,0.22)_55%,transparent_80%)] blur-2xl"
            />
            <div className="relative overflow-hidden rounded-3xl">
              <video
                className="w-full aspect-video object-cover [mask-image:linear-gradient(180deg,transparent_0%,#000_14%,#000_86%,transparent_100%)] [-webkit-mask-image:linear-gradient(180deg,transparent_0%,#000_14%,#000_86%,transparent_100%)]"
                autoPlay
                loop
                muted
                playsInline
                preload="metadata"
                poster="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/video/doctor-consult-poster.jpg"
                aria-label="Ambient LibertyMD film: a doctor gently examining a patient with a stethoscope in a soft, glowing style"
              >
                <source
                  src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/video/doctor-consult-loop.webm"
                  type="video/webm"
                />
                <source
                  src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/video/doctor-consult-loop.mp4"
                  type="video/mp4"
                />
              </video>
              {/* Left/right feather so the film blends into the page gutters on wide screens */}
              <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(90deg,rgba(247,250,245,0.6)_0%,transparent_11%,transparent_89%,rgba(247,250,245,0.6)_100%)]" />
            </div>
          </div>
        </section>

        <section className="border-t border-[#E6EDE3] bg-[linear-gradient(180deg,rgba(255,255,255,0.9),rgba(248,250,247,0.96))] px-5 py-16 sm:px-8 sm:py-20">
          <div className="mx-auto max-w-3xl text-center">
              <p className="text-xs font-bold uppercase tracking-normal text-[#2563EB]">Clinical pathway</p>
              <h2 className="mx-auto mt-3 max-w-xl text-3xl font-black tracking-normal text-[#111827] sm:text-4xl">
                Simple enough to use when you feel unwell.
              </h2>
              <p className="mx-auto mt-4 max-w-lg text-sm leading-7 text-[#5B6472]">
                A calm, structured intake that keeps the medical conversation moving.
              </p>
          </div>
          <div className="mx-auto mt-12 grid max-w-6xl gap-x-8 gap-y-9 text-left sm:grid-cols-2 lg:grid-cols-4">
            {pathwaySteps.map(([step, title, description]) => (
              <div key={step} className="border-t border-[#CBD9C6] pt-5">
                <span className="text-sm font-black text-[#2563EB]">{step}</span>
                <div className="mt-6">
                  <h3 className="font-black text-[#111827]">{title}</h3>
                  <p className="mt-2 text-sm leading-7 text-[#5B6472]">{description}</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      </main>

      {/* Exact Doctronic-Style 3D Volumetric Ribbon Footer in Blue */}
      <footer className="relative mt-24 bg-gradient-to-b from-[#EFF6FF] via-[#F0F9FF] to-[#E0F2FE] text-[#0F172A] overflow-hidden min-h-[720px] flex flex-col justify-between">
        {/* Three.js WebGL 3D Silk Wave Ribbon (Blue Theme) */}
        <LibertyMDFooterRibbon />

        {/* Top Content: Links + Trust Badges */}
        <div className="relative z-10 max-w-7xl mx-auto px-6 sm:px-10 pt-16 w-full">
          <div className="flex flex-col lg:flex-row justify-between items-start gap-12">
            {/* Left Columns */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-8 text-xs font-medium text-[#334155]">
              <div className="space-y-4">
                <p className="font-semibold text-sm text-[#0F172A]">Clinical Care</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">Symptom Checker</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Urgent Care Specialist</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Primary Telehealth</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Prescription Refills</li>
                </ul>

                <p className="font-semibold text-sm text-[#0F172A] pt-4">Help & Privacy</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">FAQs</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">GDPR Privacy Policy</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">HIPAA Compliance</li>
                </ul>
              </div>

              <div className="space-y-4">
                <p className="font-semibold text-sm text-[#0F172A]">Company</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">About LibertyMD</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Careers</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Medical Reviewers</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Team</li>
                </ul>
              </div>

              <div className="space-y-4">
                <p className="font-semibold text-sm text-[#0F172A]">Conditions</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">Respiratory Care</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Cardiovascular</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Neurology & Migraine</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">All Conditions</li>
                </ul>

                <p className="font-semibold text-sm text-[#0F172A] pt-4">Research</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">Clinical Blog</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">Peer-Reviewed RAG</li>
                </ul>
              </div>

              <div className="space-y-4">
                <p className="font-semibold text-sm text-[#0F172A]">Partnerships</p>
                <ul className="space-y-2.5">
                  <li className="hover:text-[#2563EB] cursor-pointer">Become a Partner</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">EU Health Systems</li>
                  <li className="hover:text-[#2563EB] cursor-pointer">US Insurance Network</li>
                </ul>
              </div>
            </div>

            {/* Right Side: CARIN / HIPAA / LegitScript Badges using real image URLs */}
            <div className="flex items-center gap-6 shrink-0 self-start">
              <img
                src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/carin-accredited.png"
                alt="CARIN Accredited Code of Conduct"
                className="h-16 w-auto object-contain hover:scale-105 transition-transform drop-shadow-sm"
              />
              <img
                src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/hipaa-certified.png"
                alt="HIPAA Certified"
                className="h-16 w-auto object-contain hover:scale-105 transition-transform drop-shadow-sm"
              />
              <img
                src="https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/libertymd-assets/legit_script.png"
                alt="LegitScript Certified"
                className="h-16 w-auto object-contain hover:scale-105 transition-transform drop-shadow-sm"
              />
            </div>
          </div>
        </div>

        {/* Center Patient Oath Emblem + Floating Medical Input Pill */}
        <div className="relative z-10 flex flex-col items-center justify-center py-12 px-4">
          {/* Patient Oath Circle Seal Emblem */}
          <div className="mb-10 hover:scale-105 transition-transform">
            <PatientOathEmblem className="w-48 h-48" />
          </div>

          {/* Floating Pill Search Box */}
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSend();
              window.scrollTo({ top: 0, behavior: 'smooth' });
            }}
            className="w-full max-w-2xl bg-white/90 backdrop-blur-md rounded-full p-2 pl-6 shadow-2xl border border-white/80 flex items-center gap-3 transition-all hover:shadow-3xl hover:bg-white"
          >
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask about your health..."
              className="flex-1 bg-transparent border-none text-base text-[#0F172A] placeholder-[#64748B] focus:outline-none"
            />
            <button
              type="submit"
              className="w-12 h-12 rounded-full bg-[#2563EB] hover:bg-[#1D4ED8] text-white flex items-center justify-center shadow-lg shadow-[#2563EB]/30 transition-transform active:scale-95"
            >
              <Send className="w-5 h-5" />
            </button>
          </form>
        </div>

        {/* Bottom Copyright */}
        <div className="relative z-10 max-w-7xl mx-auto px-6 sm:px-10 py-6 w-full flex flex-col sm:flex-row items-center justify-between text-xs text-[#475569] border-t border-[#CBD5E1]/60">
          <p>© {new Date().getFullYear()} LibertyMD Health Technologies. All rights reserved.</p>
          <p>Privacy-first AI triage • EU GDPR Article 9 & US HIPAA Safe Harbor</p>
        </div>
      </footer>
    </div>
  );
}
