CREATE TABLE public.trading_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker VARCHAR(10) NOT NULL,
    status VARCHAR(20) DEFAULT 'running', -- 'running', 'completed', 'failed'
    final_decision VARCHAR(50), -- e.g., 'BUY', 'HOLD', 'SELL'
    executive_summary TEXT, -- Final summary from Portfolio Manager
    investment_thesis TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.trading_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES public.trading_sessions(id) ON DELETE CASCADE,
    agent_role VARCHAR(50) NOT NULL, -- e.g., 'Market Analyst', 'Bull Debater', 'Risk Manager'
    log_type VARCHAR(20) NOT NULL, -- 'research', 'debate', 'decision', 'error'
    content TEXT NOT NULL, -- The markdown or JSON content generated by the agent
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_trading_logs_session ON public.trading_logs(session_id);

CREATE TABLE public.trading_memory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker VARCHAR(10) NOT NULL,
    trade_date DATE NOT NULL,
    decision VARCHAR(50) NOT NULL,
    raw_return DECIMAL(10, 4), -- e.g. 0.052 for 5.2%
    alpha_return DECIMAL(10, 4), -- e.g. 0.012 for 1.2% above benchmark
    reflection TEXT, -- Post-trade reflection from the LLM after time has passed
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS and setup policies so the frontend can read logs but only the service role (or Edge function) can insert
ALTER TABLE public.trading_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_memory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on trading_sessions"
ON public.trading_sessions FOR SELECT
TO authenticated, anon
USING (true);

CREATE POLICY "Enable read access for all users on trading_logs"
ON public.trading_logs FOR SELECT
TO authenticated, anon
USING (true);

CREATE POLICY "Enable read access for all users on trading_memory"
ON public.trading_memory FOR SELECT
TO authenticated, anon
USING (true);
