-- Migration: Seed Missing Wearable Parameters from CSV
INSERT INTO public.health_parameter_definitions (id, name, category, unit, axis_impact_weights) VALUES
('Acitve Calories Burnt', 'Acitve Calories Burnt', 'Wearable - activity', 'kcal', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Active Minutes', 'Active Minutes', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Basal Metabolic Rate', 'Basal Metabolic Rate', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Blood Glucose Record', 'Blood Glucose Record', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Bloood Pressure Systolic', 'Bloood Pressure Systolic', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Bloood Pressure Diastolic', 'Bloood Pressure Diastolic', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Body Temprature', 'Body Temprature', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('CervicalMucusRecord - Presence', 'CervicalMucusRecord - Presence', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('CervicalMucusRecord - Appearance', 'CervicalMucusRecord - Appearance', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Horizontal distance covered', 'Horizontal distance covered', 'Wearable - activity', 'km', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Vertical Elevation Gained', 'Vertical Elevation Gained', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('ExerciseSegment', 'ExerciseSegment', 'Wearable - activity', 'count', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('ExerciseType', 'ExerciseType', 'Wearable - activity', 'count', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('ExerciseLap', 'ExerciseLap', 'Wearable - activity', 'count', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Exercise Duration', 'Exercise Duration', 'Wearable - activity', 'min', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Exercise Calories', 'Exercise Calories', 'Wearable - activity', 'kcal', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Exercise_% Time in Heart Rate Z1', 'Exercise_% Time in Heart Rate Z1', 'Wearable - activity', '%', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Exercise_% Time in Heart Rate Z2', 'Exercise_% Time in Heart Rate Z2', 'Wearable - activity', '%', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Exercise_% Time in Heart Rate Z3', 'Exercise_% Time in Heart Rate Z3', 'Wearable - activity', '%', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Exercise_% Time in Heart Rate Z4', 'Exercise_% Time in Heart Rate Z4', 'Wearable - activity', '%', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Exercise_% Time in Heart Rate Z5', 'Exercise_% Time in Heart Rate Z5', 'Wearable - activity', '%', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Exercise Length', 'Exercise Length', 'Wearable - activity', 'km', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('VO2 Max', 'VO2 Max', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Step Count', 'Step Count', 'Wearable - activity', 'count', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Hydration Volume', 'Hydration Volume', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('IntermenstrualBleedingRecord', 'IntermenstrualBleedingRecord', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Mindfulness_Session_Type', 'Mindfulness_Session_Type', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('MINDFULNESS_DURATION_TOTAL', 'MINDFULNESS_DURATION_TOTAL', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Meal Type', 'Meal Type', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Total Energy Intake from Food', 'Total Energy Intake from Food', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('totalCarbohydrate', 'totalCarbohydrate', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('totalFat', 'totalFat', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('protein', 'protein', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Fiber', 'Fiber', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sugar', 'Sugar', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('SPO2 percentage', 'SPO2 percentage', 'Wearable - vitals', '%', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('Respiratory Rate', 'Respiratory Rate', 'Wearable - vitals', 'bpm', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('Resting Heart Rate', 'Resting Heart Rate', 'Wearable - vitals', 'bpm', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('Sleep Stage', 'Sleep Stage', 'Wearable - sleep', 'count', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Duration', 'Sleep Duration', 'Wearable - sleep', 'min', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Total Daily Calories Burned', 'Total Daily Calories Burned', 'Wearable - activity', 'kcal', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Heart Rate', 'Heart Rate', 'Wearable - vitals', 'bpm', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('Heart Rate Recovery', 'Heart Rate Recovery', 'Wearable - vitals', 'bpm', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('AtrialFibrillationBurden', 'AtrialFibrillationBurden', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Walking Heart Rate', 'Walking Heart Rate', 'Wearable - vitals', 'bpm', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('Abdominal Cramps Indicator', 'Abdominal Cramps Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Bloating Indicator', 'Bloating Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Constipation Indicator', 'Constipation Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Diarrhea Indicator', 'Diarrhea Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Heartburn Indicator', 'Heartburn Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Nausea Indicator', 'Nausea Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Vomiting Indicator', 'Vomiting Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Chills Indicator', 'Chills Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Dizziness Indicator', 'Dizziness Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Fainting Indicator', 'Fainting Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('High Fatigue Indicator', 'High Fatigue Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Fever Indicator', 'Fever Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Generalized BodyAche Indicator', 'Generalized BodyAche Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Hot Flashes Indicator', 'Hot Flashes Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Chest Tightness Or Pain Indicator', 'Chest Tightness Or Pain Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Coughing Indicator', 'Coughing Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('rapid Pounding Or Fluttering Heartbeat Indicator', 'rapid Pounding Or Fluttering Heartbeat Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('ShortnessOfBreath Indicator', 'ShortnessOfBreath Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Skipped Heartbeat Alert', 'Skipped Heartbeat Alert', 'Wearable - vitals', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('Wheezing Indicator', 'Wheezing Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('LowerBackPain Indicator', 'LowerBackPain Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Headache Indicator', 'Headache Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Memory Lapse Indicator', 'Memory Lapse Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Mood Changes Indicator', 'Mood Changes Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Loss Of Smell Indicator', 'Loss Of Smell Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Loss of Taste Indicator', 'Loss of Taste Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('RunnyNose Indicator', 'RunnyNose Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('SoreThroat Indicator', 'SoreThroat Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sinus Congestion Indicator', 'Sinus Congestion Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Breast Pain Indicator', 'Breast Pain Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Pelvic Pain Indicator', 'Pelvic Pain Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Vaginal Dryness Indicator', 'Vaginal Dryness Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Acne Indicator', 'Acne Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Dry Skin Indicator', 'Dry Skin Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Hair Loss Indicator', 'Hair Loss Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Night Sweats Indicator', 'Night Sweats Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Dramatic Sleep Changes indicator', 'Dramatic Sleep Changes indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Bladder Incontinence Indicator', 'Bladder Incontinence Indicator', 'Wearable - symptoms', 'boolean', '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Daily Step Goal', 'Daily Step Goal', 'Wearable - activity', 'count', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb),
('HB1AC_Value', 'HB1AC_Value', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Body Stress Score', 'Body Stress Score', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('physical_recovery', 'physical_recovery', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('mental_recovery', 'mental_recovery', 'Wearable - Wearable', 'count', '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('sleep_score', 'sleep_score', 'Wearable - sleep', '%', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_averageHeartRate', 'Sleep_averageHeartRate', 'Wearable - sleep', 'bpm', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_averageRespiratoryRate', 'Sleep_averageRespiratoryRate', 'Wearable - sleep', 'bpm', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_skin_temperature_max', 'Sleep_skin_temperature_max', 'Wearable - sleep', '°C', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_skin_temperature_min', 'Sleep_skin_temperature_min', 'Wearable - sleep', '°C', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_Date', 'Sleep_Date', 'Wearable - sleep', 'count', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_Quality', 'Sleep_Quality', 'Wearable - sleep', '%', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_total_snoring_time', 'Sleep_total_snoring_time', 'Wearable - sleep', 'min', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_Average SPO2%', 'Sleep_Average SPO2%', 'Wearable - sleep', '%', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_Min_SPO2', 'Sleep_Min_SPO2', 'Wearable - sleep', 'count', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep_Minutes_Low_Oxygen', 'Sleep_Minutes_Low_Oxygen', 'Wearable - sleep', 'count', '{"energy":1,"strength":0,"mind":2,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Distance Walked', 'Distance Walked', 'Wearable - activity', 'km', '{"energy":2,"strength":1,"mind":0,"resilience":0,"heart":1,"hormone":0,"environment":0}'::jsonb)
ON CONFLICT DO NOTHING;

INSERT INTO public.health_parameter_ranges (parameter_id, gender, min_age, max_age, normal_min, optimal_min, optimal_max, normal_max, critical_max) VALUES
('Acitve Calories Burnt', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Active Minutes', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Basal Metabolic Rate', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Blood Glucose Record', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Bloood Pressure Systolic', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Bloood Pressure Diastolic', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Body Temprature', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('CervicalMucusRecord - Presence', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('CervicalMucusRecord - Appearance', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Horizontal distance covered', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Vertical Elevation Gained', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('ExerciseSegment', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('ExerciseType', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('ExerciseLap', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Exercise Duration', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Exercise Calories', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Exercise_% Time in Heart Rate Z1', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Exercise_% Time in Heart Rate Z2', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Exercise_% Time in Heart Rate Z3', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Exercise_% Time in Heart Rate Z4', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Exercise_% Time in Heart Rate Z5', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Exercise Length', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('VO2 Max', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Step Count', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Hydration Volume', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('IntermenstrualBleedingRecord', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Mindfulness_Session_Type', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('MINDFULNESS_DURATION_TOTAL', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Meal Type', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Total Energy Intake from Food', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('totalCarbohydrate', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('totalFat', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('protein', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Fiber', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sugar', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('SPO2 percentage', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Respiratory Rate', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Resting Heart Rate', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep Stage', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep Duration', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Total Daily Calories Burned', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Heart Rate', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Heart Rate Recovery', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('AtrialFibrillationBurden', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Walking Heart Rate', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Abdominal Cramps Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Bloating Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Constipation Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Diarrhea Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Heartburn Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Nausea Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Vomiting Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Chills Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Dizziness Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Fainting Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('High Fatigue Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Fever Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Generalized BodyAche Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Hot Flashes Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Chest Tightness Or Pain Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Coughing Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('rapid Pounding Or Fluttering Heartbeat Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('ShortnessOfBreath Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Skipped Heartbeat Alert', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Wheezing Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('LowerBackPain Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Headache Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Memory Lapse Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Mood Changes Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Loss Of Smell Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Loss of Taste Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('RunnyNose Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('SoreThroat Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sinus Congestion Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Breast Pain Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Pelvic Pain Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Vaginal Dryness Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Acne Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Dry Skin Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Hair Loss Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Night Sweats Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Dramatic Sleep Changes indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Bladder Incontinence Indicator', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Daily Step Goal', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('HB1AC_Value', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Body Stress Score', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('physical_recovery', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('mental_recovery', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('sleep_score', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_averageHeartRate', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_averageRespiratoryRate', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_skin_temperature_max', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_skin_temperature_min', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_Date', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_Quality', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_total_snoring_time', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_Average SPO2%', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_Min_SPO2', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Sleep_Minutes_Low_Oxygen', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL),
('Distance Walked', 'ALL', 0, 120, NULL, NULL, NULL, NULL, NULL)
;
