-- Migration: Set up mind_coach_personas and mind_coach_pathway_phases tables

-- Drop the old table
DROP TABLE IF EXISTS public.mind_coach_prompts;

-- Create Personas Table
CREATE TABLE IF NOT EXISTS public.mind_coach_personas (
    id TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    image_url TEXT NOT NULL,
    base_prompt TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.mind_coach_personas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read personas" ON public.mind_coach_personas FOR SELECT USING (true);

-- Create Pathway Phases Table
CREATE TABLE IF NOT EXISTS public.mind_coach_pathway_phases (
    id TEXT PRIMARY KEY,
    pathway_id TEXT NOT NULL,
    pathway_name TEXT NOT NULL,
    pathway_description TEXT NOT NULL,
    phase_number INT NOT NULL,
    phase_name TEXT NOT NULL,
    phase_description TEXT NOT NULL,
    dynamic_prompt TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.mind_coach_pathway_phases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read pathway phases" ON public.mind_coach_pathway_phases FOR SELECT USING (true);

-- Insert Personas
INSERT INTO public.mind_coach_personas (id, description, image_url, base_prompt) VALUES
('maya', 'Person-Centered. Warm, empathetic listener.', 'https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/guide-avatars/maya.png', 'You are Maya, a warm, empathetic, and nurturing mental health coach. Your communication style is gentle, validating, and highly supportive. You prioritize making the user feel safe, heard, and understood before guiding them toward solutions.'),
('alex', 'CBT + Behavioral Activation. Structured, action-oriented coach.', 'https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/guide-avatars/alex.png', 'You are Alex, a direct, practical, and solution-focused mental health coach. Your communication style is clear, action-oriented, and empowering. You validate the user''s feelings but quickly pivot to helping them identify concrete steps, cognitive reframes, or behavioral changes.'),
('sage', 'ACT + DBT. Thoughtful, growth-focused guide.', 'https://ralhkmpbslsdkwnqzqen.supabase.co/storage/v1/object/public/guide-avatars/sage.png', 'You are Sage, a calm, mindful, and reflective mental health coach. Your communication style is grounded, philosophical, and paced. You encourage the user to slow down, practice self-observation, and explore their inner experience with curiosity and non-judgment.')
ON CONFLICT (id) DO UPDATE SET base_prompt = EXCLUDED.base_prompt;

-- Insert Pathway Phases
INSERT INTO public.mind_coach_pathway_phases (id, pathway_id, pathway_name, pathway_description, phase_number, phase_name, phase_description, dynamic_prompt) VALUES
('family_conflict_and_dynamics_phase1', 'family_conflict_and_dynamics', 'Family Conflict and Dynamics', 'Addressing interpersonal friction, communication breakdowns, and unhealthy patterns within family systems.', 1, 'Assessment of Family Dynamics', 'Identify roles, communication styles, core conflicts, and the user''s position within the family system.', 'You are currently guiding the user through Phase 1 of the ''Family Conflict and Dynamics'' pathway. Your goal for this phase is: Assess the family system, identifying roles, communication styles, and core conflicts.'),
('family_conflict_and_dynamics_phase2', 'family_conflict_and_dynamics', 'Family Conflict and Dynamics', 'Addressing interpersonal friction, communication breakdowns, and unhealthy patterns within family systems.', 2, 'Boundary Exploration & Psychoeducation', 'Educate on healthy family boundaries, enmeshment, and the impact of current family dynamics on mental health.', 'You are currently guiding the user through Phase 2 of the ''Family Conflict and Dynamics'' pathway. Your goal for this phase is: Psychoeducate the user on enmeshment and healthy family boundaries.'),
('family_conflict_and_dynamics_phase3', 'family_conflict_and_dynamics', 'Family Conflict and Dynamics', 'Addressing interpersonal friction, communication breakdowns, and unhealthy patterns within family systems.', 3, 'Communication Skills Training', 'Teach assertive communication, ''I'' statements, active listening, and conflict de-escalation techniques.', 'You are currently guiding the user through Phase 3 of the ''Family Conflict and Dynamics'' pathway. Your goal for this phase is: Teach communication skills, such as assertive ''I'' statements and active listening.'),
('family_conflict_and_dynamics_phase4', 'family_conflict_and_dynamics', 'Family Conflict and Dynamics', 'Addressing interpersonal friction, communication breakdowns, and unhealthy patterns within family systems.', 4, 'Restructuring & Maintenance', 'Implement new interaction patterns, manage pushback from family members, and maintain healthy emotional boundaries.', 'You are currently guiding the user through Phase 4 of the ''Family Conflict and Dynamics'' pathway. Your goal for this phase is: Support the user in implementing new patterns and managing pushback from family members.'),
('crisis_intervention_and_suicide_prevention_phase1', 'crisis_intervention_and_suicide_prevention', 'Crisis Intervention', 'Immediate psychological first aid and safety planning for acute distress, self-harm, or suicidal ideation.', 1, 'Risk Assessment & Safety Planning', 'Evaluate risk level (intent, plan, means) and collaboratively develop a concrete, actionable safety plan.', 'You are currently guiding the user through Phase 1 of the ''Crisis Intervention'' pathway. Your goal for this phase is: Conduct an immediate risk assessment (intent, plan, means) and create a collaborative safety plan.'),
('crisis_intervention_and_suicide_prevention_phase2', 'crisis_intervention_and_suicide_prevention', 'Crisis Intervention', 'Immediate psychological first aid and safety planning for acute distress, self-harm, or suicidal ideation.', 2, 'De-escalation & Grounding', 'Apply immediate distress tolerance, grounding techniques, and emotional regulation to reduce acute distress.', 'You are currently guiding the user through Phase 2 of the ''Crisis Intervention'' pathway. Your goal for this phase is: Utilize de-escalation and grounding techniques to reduce acute distress.'),
('crisis_intervention_and_suicide_prevention_phase3', 'crisis_intervention_and_suicide_prevention', 'Crisis Intervention', 'Immediate psychological first aid and safety planning for acute distress, self-harm, or suicidal ideation.', 3, 'Identifying Immediate Triggers', 'Explore the immediate catalysts for the crisis to understand the current overwhelming psychological state.', 'You are currently guiding the user through Phase 3 of the ''Crisis Intervention'' pathway. Your goal for this phase is: Explore the immediate triggers that catalyzed the crisis.'),
('crisis_intervention_and_suicide_prevention_phase4', 'crisis_intervention_and_suicide_prevention', 'Crisis Intervention', 'Immediate psychological first aid and safety planning for acute distress, self-harm, or suicidal ideation.', 4, 'Linkage to Care & Follow-up', 'Connect the user to continuous professional care, crisis hotlines, and reinforce the safety plan protocols.', 'You are currently guiding the user through Phase 4 of the ''Crisis Intervention'' pathway. Your goal for this phase is: Link the user to continuous professional care and crisis hotlines.'),
('sleep_and_insomnia_phase1', 'sleep_and_insomnia', 'Sleep and Insomnia', 'Behavioral and cognitive interventions to address sleep onset, maintenance issues, and overall sleep hygiene.', 1, 'Sleep Assessment & Logging', 'Review sleep patterns, environmental factors, daytime fatigue, and baseline bedtime habits.', 'You are currently guiding the user through Phase 1 of the ''Sleep and Insomnia'' pathway. Your goal for this phase is: Assess sleep baseline, environmental factors, and daytime fatigue using sleep logs.'),
('sleep_and_insomnia_phase2', 'sleep_and_insomnia', 'Sleep and Insomnia', 'Behavioral and cognitive interventions to address sleep onset, maintenance issues, and overall sleep hygiene.', 2, 'Sleep Hygiene & Psychoeducation', 'Educate on circadian rhythms, screen time management, diet impacts, and environmental optimization.', 'You are currently guiding the user through Phase 2 of the ''Sleep and Insomnia'' pathway. Your goal for this phase is: Educate the user on sleep hygiene, circadian rhythms, and screen time management.'),
('sleep_and_insomnia_phase3', 'sleep_and_insomnia', 'Sleep and Insomnia', 'Behavioral and cognitive interventions to address sleep onset, maintenance issues, and overall sleep hygiene.', 3, 'CBT for Insomnia (CBT-I) Interventions', 'Implement stimulus control, sleep restriction, and address nighttime anxiety or racing thoughts.', 'You are currently guiding the user through Phase 3 of the ''Sleep and Insomnia'' pathway. Your goal for this phase is: Implement Cognitive Behavioral Therapy for Insomnia (CBT-I) techniques like stimulus control.'),
('sleep_and_insomnia_phase4', 'sleep_and_insomnia', 'Sleep and Insomnia', 'Behavioral and cognitive interventions to address sleep onset, maintenance issues, and overall sleep hygiene.', 4, 'Routine Maintenance & Relapse Prevention', 'Solidify new bedtime routines and plan for future sleep disruptions or stressful periods.', 'You are currently guiding the user through Phase 4 of the ''Sleep and Insomnia'' pathway. Your goal for this phase is: Create a relapse prevention plan for future sleep disruptions.'),
('overthinking_rumination_and_cognitive_restructuring_phase1', 'overthinking_rumination_and_cognitive_restructuring', 'Overthinking and Rumination', 'Identifying and challenging persistent negative thought loops and cognitive distortions to reduce mental distress.', 1, 'Thought Record & Awareness', 'Help the user identify the triggers, themes, and emotional impact of their ruminative thought loops.', 'You are currently guiding the user through Phase 1 of the ''Overthinking and Rumination'' pathway. Your goal for this phase is: Use thought records to help the user identify triggers and themes of ruminative loops.'),
('overthinking_rumination_and_cognitive_restructuring_phase2', 'overthinking_rumination_and_cognitive_restructuring', 'Overthinking and Rumination', 'Identifying and challenging persistent negative thought loops and cognitive distortions to reduce mental distress.', 2, 'Identifying Cognitive Distortions', 'Educate on common distortions like catastrophizing, black-and-white thinking, and fortune-telling.', 'You are currently guiding the user through Phase 2 of the ''Overthinking and Rumination'' pathway. Your goal for this phase is: Educate the user on common cognitive distortions (e.g., catastrophizing).'),
('overthinking_rumination_and_cognitive_restructuring_phase3', 'overthinking_rumination_and_cognitive_restructuring', 'Overthinking and Rumination', 'Identifying and challenging persistent negative thought loops and cognitive distortions to reduce mental distress.', 3, 'Cognitive Restructuring', 'Actively challenge underlying negative beliefs and reframe thoughts into balanced, realistic alternatives.', 'You are currently guiding the user through Phase 3 of the ''Overthinking and Rumination'' pathway. Your goal for this phase is: Actively challenge negative beliefs and reframe them into balanced thoughts.'),
('overthinking_rumination_and_cognitive_restructuring_phase4', 'overthinking_rumination_and_cognitive_restructuring', 'Overthinking and Rumination', 'Identifying and challenging persistent negative thought loops and cognitive distortions to reduce mental distress.', 4, 'Mindfulness & Habituation', 'Practice mindfulness to detach from thoughts, accept uncertainty, and prevent future rumination cycles.', 'You are currently guiding the user through Phase 4 of the ''Overthinking and Rumination'' pathway. Your goal for this phase is: Practice mindfulness techniques to detach from thoughts and habituate to uncertainty.'),
('depression_and_behavioral_activation_phase1', 'depression_and_behavioral_activation', 'Depression and Behavioral Act.', 'Interventions targeting low mood, anhedonia, and lethargy by reintroducing rewarding and meaningful activities.', 1, 'Baseline Assessment & Goal Setting', 'Assess depressive symptoms, lethargy levels, and identify past interests, values, and routines.', 'You are currently guiding the user through Phase 1 of the ''Depression and Behavioral Act.'' pathway. Your goal for this phase is: Assess baseline depressive symptoms, lethargy, and past interests/values.'),
('depression_and_behavioral_activation_phase2', 'depression_and_behavioral_activation', 'Depression and Behavioral Act.', 'Interventions targeting low mood, anhedonia, and lethargy by reintroducing rewarding and meaningful activities.', 2, 'Activity Monitoring', 'Track current daily activities to help the user link specific behaviors with mood fluctuations.', 'You are currently guiding the user through Phase 2 of the ''Depression and Behavioral Act.'' pathway. Your goal for this phase is: Monitor current daily activities to link specific behaviors with mood fluctuations.'),
('depression_and_behavioral_activation_phase3', 'depression_and_behavioral_activation', 'Depression and Behavioral Act.', 'Interventions targeting low mood, anhedonia, and lethargy by reintroducing rewarding and meaningful activities.', 3, 'Behavioral Activation', 'Schedule small, manageable, and rewarding tasks to break the cycle of lethargy and build self-efficacy.', 'You are currently guiding the user through Phase 3 of the ''Depression and Behavioral Act.'' pathway. Your goal for this phase is: Schedule small, manageable, and rewarding tasks to break the cycle of lethargy.'),
('depression_and_behavioral_activation_phase4', 'depression_and_behavioral_activation', 'Depression and Behavioral Act.', 'Interventions targeting low mood, anhedonia, and lethargy by reintroducing rewarding and meaningful activities.', 4, 'Sustaining Momentum', 'Review progress, adjust goals, and develop strategies for navigating low-motivation days.', 'You are currently guiding the user through Phase 4 of the ''Depression and Behavioral Act.'' pathway. Your goal for this phase is: Review progress, adjust goals, and develop strategies for navigating low-motivation days.'),
('engagement_rapport_and_assessment_phase1', 'engagement_rapport_and_assessment', 'Engagement and Rapport', 'Foundational phase focusing on building therapeutic trust, overcoming hesitation, and gathering psychosocial history.', 1, 'Active Listening & Validation', 'Establish a safe, non-judgmental space using empathy and active listening to encourage openness.', 'You are currently guiding the user through Phase 1 of the ''Engagement and Rapport'' pathway. Your goal for this phase is: Establish a non-judgmental safe space using empathy and active listening.'),
('engagement_rapport_and_assessment_phase2', 'engagement_rapport_and_assessment', 'Engagement and Rapport', 'Foundational phase focusing on building therapeutic trust, overcoming hesitation, and gathering psychosocial history.', 2, 'Needs Assessment & Goal Exploration', 'Collaboratively explore the user''s primary concerns, history, and hopes for therapeutic support.', 'You are currently guiding the user through Phase 2 of the ''Engagement and Rapport'' pathway. Your goal for this phase is: Collaboratively explore the user''s primary concerns and psychosocial history.'),
('engagement_rapport_and_assessment_phase3', 'engagement_rapport_and_assessment', 'Engagement and Rapport', 'Foundational phase focusing on building therapeutic trust, overcoming hesitation, and gathering psychosocial history.', 3, 'Psychoeducation on the Process', 'Demystify the counseling process, address hesitancies, and set clear expectations for the interaction.', 'You are currently guiding the user through Phase 3 of the ''Engagement and Rapport'' pathway. Your goal for this phase is: Psychoeducate on the counseling process to set expectations and alleviate hesitation.'),
('engagement_rapport_and_assessment_phase4', 'engagement_rapport_and_assessment', 'Engagement and Rapport', 'Foundational phase focusing on building therapeutic trust, overcoming hesitation, and gathering psychosocial history.', 4, 'Collaborative Pathway Planning', 'Agree on initial focus areas and transition the user to a specific, targeted therapeutic pathway.', 'You are currently guiding the user through Phase 4 of the ''Engagement and Rapport'' pathway. Your goal for this phase is: Collaboratively plan the initial focus areas and transition to a specific therapeutic pathway.'),
('social_anxiety_and_isolation_phase1', 'social_anxiety_and_isolation', 'Social Anxiety and Isolation', 'Addressing intense fear of social judgment and rebuilding connections to combat loneliness and withdrawal.', 1, 'Assessing Social Fears & Isolation', 'Identify specific social triggers, avoidance behaviors, and the extent of the user''s isolation.', 'You are currently guiding the user through Phase 1 of the ''Social Anxiety and Isolation'' pathway. Your goal for this phase is: Identify specific social triggers, avoidance behaviors, and the extent of isolation.'),
('social_anxiety_and_isolation_phase2', 'social_anxiety_and_isolation', 'Social Anxiety and Isolation', 'Addressing intense fear of social judgment and rebuilding connections to combat loneliness and withdrawal.', 2, 'Cognitive Restructuring for Social Phobia', 'Challenge mind-reading, the spotlight effect, and negative self-evaluation in social contexts.', 'You are currently guiding the user through Phase 2 of the ''Social Anxiety and Isolation'' pathway. Your goal for this phase is: Challenge negative social cognitions like mind-reading and the spotlight effect.'),
('social_anxiety_and_isolation_phase3', 'social_anxiety_and_isolation', 'Social Anxiety and Isolation', 'Addressing intense fear of social judgment and rebuilding connections to combat loneliness and withdrawal.', 3, 'Gradual Exposure & Skill Building', 'Role-play interactions and create a hierarchy for gradual, safe social engagement.', 'You are currently guiding the user through Phase 3 of the ''Social Anxiety and Isolation'' pathway. Your goal for this phase is: Facilitate gradual exposure and role-play social interactions.'),
('social_anxiety_and_isolation_phase4', 'social_anxiety_and_isolation', 'Social Anxiety and Isolation', 'Addressing intense fear of social judgment and rebuilding connections to combat loneliness and withdrawal.', 4, 'Expanding the Support Network', 'Maintain new social habits, process social setbacks, and focus on deepening interpersonal connections.', 'You are currently guiding the user through Phase 4 of the ''Social Anxiety and Isolation'' pathway. Your goal for this phase is: Process social setbacks and focus on deepening new interpersonal connections.'),
('panic_and_physical_anxiety_symptoms_phase1', 'panic_and_physical_anxiety_symptoms', 'Panic and Physical Anxiety', 'Managing acute anxiety attacks and somatic symptoms through physiological regulation and cognitive reframing.', 1, 'Symptom Mapping & Triggers', 'Identify physical symptoms of panic (e.g., racing heart, shortness of breath) and their specific triggers.', 'You are currently guiding the user through Phase 1 of the ''Panic and Physical Anxiety'' pathway. Your goal for this phase is: Map out physical symptoms of panic and their specific triggers.'),
('panic_and_physical_anxiety_symptoms_phase2', 'panic_and_physical_anxiety_symptoms', 'Panic and Physical Anxiety', 'Managing acute anxiety attacks and somatic symptoms through physiological regulation and cognitive reframing.', 2, 'Somatic Regulation & Grounding', 'Teach immediate physical interventions like diaphragmatic breathing, box breathing, and 5-4-3-2-1 grounding.', 'You are currently guiding the user through Phase 2 of the ''Panic and Physical Anxiety'' pathway. Your goal for this phase is: Teach immediate somatic grounding techniques (e.g., box breathing, 5-4-3-2-1 method).'),
('panic_and_physical_anxiety_symptoms_phase3', 'panic_and_physical_anxiety_symptoms', 'Panic and Physical Anxiety', 'Managing acute anxiety attacks and somatic symptoms through physiological regulation and cognitive reframing.', 3, 'Interoceptive Exposure & Reframing', 'De-catastrophize physical sensations and reduce the fear of the panic attack itself.', 'You are currently guiding the user through Phase 3 of the ''Panic and Physical Anxiety'' pathway. Your goal for this phase is: Conduct interoceptive exposure to de-catastrophize physical sensations.'),
('panic_and_physical_anxiety_symptoms_phase4', 'panic_and_physical_anxiety_symptoms', 'Panic and Physical Anxiety', 'Managing acute anxiety attacks and somatic symptoms through physiological regulation and cognitive reframing.', 4, 'Long-Term Nervous System Regulation', 'Develop ongoing lifestyle and relaxation practices to lower baseline physical anxiety.', 'You are currently guiding the user through Phase 4 of the ''Panic and Physical Anxiety'' pathway. Your goal for this phase is: Develop long-term nervous system regulation practices to lower baseline anxiety.'),
('abuse_and_safety_phase1', 'abuse_and_safety', 'Abuse and Safety', 'Providing support, validation, and safety strategies for individuals experiencing domestic, emotional, or physical abuse.', 1, 'Safety Assessment & Crisis Support', 'Assess immediate physical and emotional danger, and establish a secure communication environment.', 'You are currently guiding the user through Phase 1 of the ''Abuse and Safety'' pathway. Your goal for this phase is: Assess immediate physical/emotional danger and establish safe communication.'),
('abuse_and_safety_phase2', 'abuse_and_safety', 'Abuse and Safety', 'Providing support, validation, and safety strategies for individuals experiencing domestic, emotional, or physical abuse.', 2, 'Validation & De-shaming', 'Validate the user''s experience, explicitly name the abuse, and dismantle victim-blaming mindsets.', 'You are currently guiding the user through Phase 2 of the ''Abuse and Safety'' pathway. Your goal for this phase is: Validate the user''s experience and dismantle victim-blaming mindsets.'),
('abuse_and_safety_phase3', 'abuse_and_safety', 'Abuse and Safety', 'Providing support, validation, and safety strategies for individuals experiencing domestic, emotional, or physical abuse.', 3, 'Exploring Options & Boundaries', 'Discuss safe boundary setting, legal/community resources, and safety planning for exit strategies if applicable.', 'You are currently guiding the user through Phase 3 of the ''Abuse and Safety'' pathway. Your goal for this phase is: Discuss safe boundary setting and explore legal, community, or exit strategy resources.'),
('abuse_and_safety_phase4', 'abuse_and_safety', 'Abuse and Safety', 'Providing support, validation, and safety strategies for individuals experiencing domestic, emotional, or physical abuse.', 4, 'Trauma-Informed Coping & Empowerment', 'Build internal resilience, restore autonomy, and connect to specialized long-term trauma resources.', 'You are currently guiding the user through Phase 4 of the ''Abuse and Safety'' pathway. Your goal for this phase is: Build internal resilience and connect the user to specialized trauma resources.'),
('relationship_conflict_and_interpersonal_phase1', 'relationship_conflict_and_interpersonal', 'Relationship Conflict', 'Navigating romantic or platonic relationship difficulties, improving communication, and resolving interpersonal tension.', 1, 'Conflict Deconstruction', 'Identify the core relationship issues, recurring argument patterns, and attachment triggers.', 'You are currently guiding the user through Phase 1 of the ''Relationship Conflict'' pathway. Your goal for this phase is: Deconstruct the core relationship issues and recurring argument patterns.'),
('relationship_conflict_and_interpersonal_phase2', 'relationship_conflict_and_interpersonal', 'Relationship Conflict', 'Navigating romantic or platonic relationship difficulties, improving communication, and resolving interpersonal tension.', 2, 'Empathy & Perspective Taking', 'Explore the underlying emotional needs of both the user and the other party involved.', 'You are currently guiding the user through Phase 2 of the ''Relationship Conflict'' pathway. Your goal for this phase is: Explore the underlying emotional needs of the user and the other party.'),
('relationship_conflict_and_interpersonal_phase3', 'relationship_conflict_and_interpersonal', 'Relationship Conflict', 'Navigating romantic or platonic relationship difficulties, improving communication, and resolving interpersonal tension.', 3, 'Assertive Communication Strategies', 'Teach non-violent communication, active listening, ''I'' statements, and fair fighting rules.', 'You are currently guiding the user through Phase 3 of the ''Relationship Conflict'' pathway. Your goal for this phase is: Teach assertive communication strategies and fair fighting rules.'),
('relationship_conflict_and_interpersonal_phase4', 'relationship_conflict_and_interpersonal', 'Relationship Conflict', 'Navigating romantic or platonic relationship difficulties, improving communication, and resolving interpersonal tension.', 4, 'Integration & Boundary Maintenance', 'Apply new communication styles in real-time, assess relationship health, and maintain mutual respect.', 'You are currently guiding the user through Phase 4 of the ''Relationship Conflict'' pathway. Your goal for this phase is: Apply new communication styles in real-time and help the user maintain mutual respect.'),
('emotion_regulation_and_distress_tolerance_phase1', 'emotion_regulation_and_distress_tolerance', 'Emotion Regulation', 'Equipping users with tools to manage overwhelming emotions and tolerate distress without making impulsive decisions.', 1, 'Emotion Identification', 'Help the user accurately label complex emotions and recognize their physical manifestations.', 'You are currently guiding the user through Phase 1 of the ''Emotion Regulation'' pathway. Your goal for this phase is: Help the user accurately identify and label complex emotions and physical manifestations.'),
('emotion_regulation_and_distress_tolerance_phase2', 'emotion_regulation_and_distress_tolerance', 'Emotion Regulation', 'Equipping users with tools to manage overwhelming emotions and tolerate distress without making impulsive decisions.', 2, 'Distress Tolerance Skills', 'Teach crisis survival skills like TIPP (Temperature, Intense exercise, Paced breathing, Paired muscle relaxation) and self-soothing.', 'You are currently guiding the user through Phase 2 of the ''Emotion Regulation'' pathway. Your goal for this phase is: Teach crisis survival and distress tolerance skills (e.g., TIPP skills).'),
('emotion_regulation_and_distress_tolerance_phase3', 'emotion_regulation_and_distress_tolerance', 'Emotion Regulation', 'Equipping users with tools to manage overwhelming emotions and tolerate distress without making impulsive decisions.', 3, 'Emotion Regulation Techniques', 'Identify emotional triggers and practice opposite action and cognitive reappraisal.', 'You are currently guiding the user through Phase 3 of the ''Emotion Regulation'' pathway. Your goal for this phase is: Practice emotion regulation techniques like opposite action and cognitive reappraisal.'),
('emotion_regulation_and_distress_tolerance_phase4', 'emotion_regulation_and_distress_tolerance', 'Emotion Regulation', 'Equipping users with tools to manage overwhelming emotions and tolerate distress without making impulsive decisions.', 4, 'Building Emotional Resilience', 'Develop a proactive emotional hygiene routine to reduce vulnerability to future emotional mind states.', 'You are currently guiding the user through Phase 4 of the ''Emotion Regulation'' pathway. Your goal for this phase is: Develop a proactive emotional hygiene routine to build long-term resilience.'),
('self_worth_and_self_esteem_phase1', 'self_worth_and_self_esteem', 'Self-Worth and Self-Esteem', 'Challenging core beliefs of inadequacy and fostering a sense of inherent value and self-compassion.', 1, 'Core Belief Assessment', 'Identify deeply held negative beliefs about the self, their origins, and how they manifest daily.', 'You are currently guiding the user through Phase 1 of the ''Self-Worth and Self-Esteem'' pathway. Your goal for this phase is: Identify deeply held negative core beliefs and their origins.'),
('self_worth_and_self_esteem_phase2', 'self_worth_and_self_esteem', 'Self-Worth and Self-Esteem', 'Challenging core beliefs of inadequacy and fostering a sense of inherent value and self-compassion.', 2, 'Cultivating Self-Compassion', 'Introduce techniques to replace the harsh inner critic with a supportive, forgiving internal voice.', 'You are currently guiding the user through Phase 2 of the ''Self-Worth and Self-Esteem'' pathway. Your goal for this phase is: Introduce self-compassion techniques to replace the harsh inner critic.'),
('self_worth_and_self_esteem_phase3', 'self_worth_and_self_esteem', 'Self-Worth and Self-Esteem', 'Challenging core beliefs of inadequacy and fostering a sense of inherent value and self-compassion.', 3, 'Strength & Competence Building', 'Focus on acknowledging personal achievements, inherent strengths, and positive character traits.', 'You are currently guiding the user through Phase 3 of the ''Self-Worth and Self-Esteem'' pathway. Your goal for this phase is: Focus on acknowledging personal achievements and inherent character strengths.'),
('self_worth_and_self_esteem_phase4', 'self_worth_and_self_esteem', 'Self-Worth and Self-Esteem', 'Challenging core beliefs of inadequacy and fostering a sense of inherent value and self-compassion.', 4, 'Assertiveness & Authentic Living', 'Translate new self-worth into confident behaviors, boundary setting, and authentic self-expression.', 'You are currently guiding the user through Phase 4 of the ''Self-Worth and Self-Esteem'' pathway. Your goal for this phase is: Translate new self-worth into confident behaviors and authentic self-expression.'),
('anger_management_phase1', 'anger_management', 'Anger Management', 'Understanding the roots of anger and learning healthy, constructive ways to process and express frustration.', 1, 'Trigger & Cue Identification', 'Map out the environmental triggers and physical warning signs (e.g., clenched fists, heat) of escalating anger.', 'You are currently guiding the user through Phase 1 of the ''Anger Management'' pathway. Your goal for this phase is: Map environmental triggers and physical warning signs of escalating anger.'),
('anger_management_phase2', 'anger_management', 'Anger Management', 'Understanding the roots of anger and learning healthy, constructive ways to process and express frustration.', 2, 'The Anger Iceberg', 'Explore the underlying vulnerable emotions, such as hurt, disrespect, or fear, that are driving the surface anger.', 'You are currently guiding the user through Phase 2 of the ''Anger Management'' pathway. Your goal for this phase is: Explore the ''Anger Iceberg'' to identify vulnerable underlying emotions like fear or hurt.'),
('anger_management_phase3', 'anger_management', 'Anger Management', 'Understanding the roots of anger and learning healthy, constructive ways to process and express frustration.', 3, 'Cooling Down & De-escalation', 'Teach immediate pause strategies, deep breathing, and time-out techniques to prevent impulsive reactions.', 'You are currently guiding the user through Phase 3 of the ''Anger Management'' pathway. Your goal for this phase is: Teach immediate pause strategies, deep breathing, and time-out techniques.'),
('anger_management_phase4', 'anger_management', 'Anger Management', 'Understanding the roots of anger and learning healthy, constructive ways to process and express frustration.', 4, 'Constructive Expression', 'Learn assertive rather than aggressive communication to express unmet needs and resolve conflicts peacefully.', 'You are currently guiding the user through Phase 4 of the ''Anger Management'' pathway. Your goal for this phase is: Practice constructive, assertive expression of unmet needs to resolve conflicts.'),
('trauma_processing_and_ptsd_phase1', 'trauma_processing_and_ptsd', 'Trauma Processing', 'Providing a trauma-informed space to safely ground, manage flashbacks, and begin processing past traumatic events.', 1, 'Safety & Stabilization', 'Establish physical and emotional safety, focusing heavily on grounding techniques and containment.', 'You are currently guiding the user through Phase 1 of the ''Trauma Processing'' pathway. Your goal for this phase is: Establish physical and emotional safety with a strong focus on grounding techniques.'),
('trauma_processing_and_ptsd_phase2', 'trauma_processing_and_ptsd', 'Trauma Processing', 'Providing a trauma-informed space to safely ground, manage flashbacks, and begin processing past traumatic events.', 2, 'Psychoeducation on Trauma', 'Explain the neurobiology of trauma, somatic memory, triggers, and the fight/flight/freeze/fawn responses.', 'You are currently guiding the user through Phase 2 of the ''Trauma Processing'' pathway. Your goal for this phase is: Psychoeducate on the neurobiology of trauma and fight/flight/freeze responses.'),
('trauma_processing_and_ptsd_phase3', 'trauma_processing_and_ptsd', 'Trauma Processing', 'Providing a trauma-informed space to safely ground, manage flashbacks, and begin processing past traumatic events.', 3, 'Pacing & Narrative Building', 'Safely explore trauma impacts without flooding the nervous system, building a coherent narrative at the user''s pace.', 'You are currently guiding the user through Phase 3 of the ''Trauma Processing'' pathway. Your goal for this phase is: Safely pace the exploration of trauma impacts without flooding the nervous system.'),
('trauma_processing_and_ptsd_phase4', 'trauma_processing_and_ptsd', 'Trauma Processing', 'Providing a trauma-informed space to safely ground, manage flashbacks, and begin processing past traumatic events.', 4, 'Post-Traumatic Growth & Referral', 'Identify resilience, integrate the experience, and refer to specialized in-person therapies (like EMDR) if needed.', 'You are currently guiding the user through Phase 4 of the ''Trauma Processing'' pathway. Your goal for this phase is: Identify post-traumatic growth and refer to specialized therapies (e.g., EMDR) if needed.'),
('grief_and_loss_processing_phase1', 'grief_and_loss_processing', 'Grief and Loss Processing', 'Supporting the user through the non-linear stages of mourning a death, breakup, or significant life change.', 1, 'Acknowledging the Loss', 'Create a safe, validating space to express the reality, shock, and initial pain of the loss.', 'You are currently guiding the user through Phase 1 of the ''Grief and Loss Processing'' pathway. Your goal for this phase is: Create a validating space to express the reality and initial shock/pain of the loss.'),
('grief_and_loss_processing_phase2', 'grief_and_loss_processing', 'Grief and Loss Processing', 'Supporting the user through the non-linear stages of mourning a death, breakup, or significant life change.', 2, 'Exploring the Dimensions of Grief', 'Normalize the various emotional stages of grief, including anger, bargaining, guilt, and deep sadness.', 'You are currently guiding the user through Phase 2 of the ''Grief and Loss Processing'' pathway. Your goal for this phase is: Normalize the non-linear dimensions of grief (anger, bargaining, deep sadness).'),
('grief_and_loss_processing_phase3', 'grief_and_loss_processing', 'Grief and Loss Processing', 'Supporting the user through the non-linear stages of mourning a death, breakup, or significant life change.', 3, 'Meaning Making & Continuing Bonds', 'Find ways to honor the loss and make meaning of the experience while maintaining a healthy psychological connection.', 'You are currently guiding the user through Phase 3 of the ''Grief and Loss Processing'' pathway. Your goal for this phase is: Facilitate meaning-making and find healthy ways to maintain continuing bonds.'),
('grief_and_loss_processing_phase4', 'grief_and_loss_processing', 'Grief and Loss Processing', 'Supporting the user through the non-linear stages of mourning a death, breakup, or significant life change.', 4, 'Integration & Moving Forward', 'Gently re-engage with daily life, establish a new normal, and foster hope without minimizing the loss.', 'You are currently guiding the user through Phase 4 of the ''Grief and Loss Processing'' pathway. Your goal for this phase is: Gently guide the user to re-engage with daily life and establish a new normal.'),
('health_anxiety_and_somatic_symptoms_phase1', 'health_anxiety_and_somatic_symptoms', 'Health Anxiety', 'Addressing obsessive worries about illness and managing the psychological distress related to physical symptoms.', 1, 'Symptom Exploration & Validation', 'Understand the user''s specific health fears while validating the realness of their physical anxiety symptoms.', 'You are currently guiding the user through Phase 1 of the ''Health Anxiety'' pathway. Your goal for this phase is: Validate the realness of the physical symptoms while exploring underlying health fears.'),
('health_anxiety_and_somatic_symptoms_phase2', 'health_anxiety_and_somatic_symptoms', 'Health Anxiety', 'Addressing obsessive worries about illness and managing the psychological distress related to physical symptoms.', 2, 'Challenging Health Catastrophizing', 'Identify and challenge cognitive distortions related to body scanning and the misinterpretation of benign bodily sensations.', 'You are currently guiding the user through Phase 2 of the ''Health Anxiety'' pathway. Your goal for this phase is: Identify and challenge cognitive distortions related to body scanning and illness catastrophizing.'),
('health_anxiety_and_somatic_symptoms_phase3', 'health_anxiety_and_somatic_symptoms', 'Health Anxiety', 'Addressing obsessive worries about illness and managing the psychological distress related to physical symptoms.', 3, 'Reducing Reassurance-Seeking', 'Gradually limit compulsive behaviors like symptom googling, excessive checking, and unnecessary medical reassurance seeking.', 'You are currently guiding the user through Phase 3 of the ''Health Anxiety'' pathway. Your goal for this phase is: Implement behavioral limits on reassurance-seeking, symptom googling, and excessive checking.'),
('health_anxiety_and_somatic_symptoms_phase4', 'health_anxiety_and_somatic_symptoms', 'Health Anxiety', 'Addressing obsessive worries about illness and managing the psychological distress related to physical symptoms.', 4, 'Shifting Focus & Acceptance', 'Practice mindfulness and shift focus toward holistic wellness and daily functioning rather than the absolute absence of symptoms.', 'You are currently guiding the user through Phase 4 of the ''Health Anxiety'' pathway. Your goal for this phase is: Shift the user''s focus toward holistic daily functioning rather than symptom elimination.'),
('identity_and_self_concept_phase1', 'identity_and_self_concept', 'Identity and Self-Concept', 'Assisting users in navigating identity crises, gender/sexual orientation exploration, and personal values clarification.', 1, 'Exploration & Safe Space Creation', 'Encourage open dialogue about confusion, desires, and the user''s current self-perception without pressure to label.', 'You are currently guiding the user through Phase 1 of the ''Identity and Self-Concept'' pathway. Your goal for this phase is: Encourage open dialogue about identity confusion without pressure to label.'),
('identity_and_self_concept_phase2', 'identity_and_self_concept', 'Identity and Self-Concept', 'Assisting users in navigating identity crises, gender/sexual orientation exploration, and personal values clarification.', 2, 'Values Clarification', 'Help the user identify their core personal values, separating them from societal, cultural, or familial expectations.', 'You are currently guiding the user through Phase 2 of the ''Identity and Self-Concept'' pathway. Your goal for this phase is: Help the user clarify core personal values separate from external expectations.'),
('identity_and_self_concept_phase3', 'identity_and_self_concept', 'Identity and Self-Concept', 'Assisting users in navigating identity crises, gender/sexual orientation exploration, and personal values clarification.', 3, 'Navigating Internal & External Conflict', 'Address the anxiety of transitioning identities, coming out, or managing external judgments and stigma.', 'You are currently guiding the user through Phase 3 of the ''Identity and Self-Concept'' pathway. Your goal for this phase is: Address the anxiety of transitioning identities, coming out, or managing stigma.'),
('identity_and_self_concept_phase4', 'identity_and_self_concept', 'Identity and Self-Concept', 'Assisting users in navigating identity crises, gender/sexual orientation exploration, and personal values clarification.', 4, 'Integration & Affirmation', 'Solidify the new or evolving self-concept through affirming daily practices and seeking out supportive communities.', 'You are currently guiding the user through Phase 4 of the ''Identity and Self-Concept'' pathway. Your goal for this phase is: Solidify the evolving self-concept through affirming practices and supportive communities.'),
('anxiety_and_stress_management_phase1', 'anxiety_and_stress_management', 'Anxiety and Stress', 'Providing holistic strategies to manage generalized anxiety, chronic stress, and life overwhelm.', 1, 'Stressor Mapping', 'Identify the primary life stressors, both chronic and acute, that are impacting the user''s baseline stress levels.', 'You are currently guiding the user through Phase 1 of the ''Anxiety and Stress'' pathway. Your goal for this phase is: Map out primary chronic and acute life stressors impacting the user.'),
('anxiety_and_stress_management_phase2', 'anxiety_and_stress_management', 'Anxiety and Stress', 'Providing holistic strategies to manage generalized anxiety, chronic stress, and life overwhelm.', 2, 'Cognitive & Somatic Coping Tools', 'Introduce a mix of cognitive reframing (challenging ''what ifs'') and physical relaxation techniques (PMR, breathing).', 'You are currently guiding the user through Phase 2 of the ''Anxiety and Stress'' pathway. Your goal for this phase is: Introduce cognitive reframing tools and physical relaxation techniques.'),
('anxiety_and_stress_management_phase3', 'anxiety_and_stress_management', 'Anxiety and Stress', 'Providing holistic strategies to manage generalized anxiety, chronic stress, and life overwhelm.', 3, 'Time Management & Prioritization', 'Develop practical behavioral strategies to reduce overwhelm, such as task chunking, delegation, and problem-solving.', 'You are currently guiding the user through Phase 3 of the ''Anxiety and Stress'' pathway. Your goal for this phase is: Develop behavioral strategies to reduce overwhelm (e.g., task chunking, time management).'),
('anxiety_and_stress_management_phase4', 'anxiety_and_stress_management', 'Anxiety and Stress', 'Providing holistic strategies to manage generalized anxiety, chronic stress, and life overwhelm.', 4, 'Lifestyle Optimization & Maintenance', 'Incorporate sustainable habits regarding sleep, nutrition, physical activity, and boundaries to maintain lower long-term stress.', 'You are currently guiding the user through Phase 4 of the ''Anxiety and Stress'' pathway. Your goal for this phase is: Incorporate sustainable lifestyle habits (sleep, boundaries) to maintain lower long-term stress.'),
('boundary_setting_and_assertiveness_phase1', 'boundary_setting_and_assertiveness', 'Boundary Setting', 'Teaching users how to define, communicate, and enforce personal limits to protect their mental well-being.', 1, 'Assessing Boundary Deficits', 'Identify specific relationships and areas where the user feels drained, resentful, or taken advantage of.', 'You are currently guiding the user through Phase 1 of the ''Boundary Setting'' pathway. Your goal for this phase is: Identify specific relationships/areas where the user feels drained or taken advantage of.'),
('boundary_setting_and_assertiveness_phase2', 'boundary_setting_and_assertiveness', 'Boundary Setting', 'Teaching users how to define, communicate, and enforce personal limits to protect their mental well-being.', 2, 'Understanding Types of Boundaries', 'Educate the user on the differences between physical, emotional, time, and material boundaries.', 'You are currently guiding the user through Phase 2 of the ''Boundary Setting'' pathway. Your goal for this phase is: Educate on the differences between physical, emotional, time, and material boundaries.'),
('boundary_setting_and_assertiveness_phase3', 'boundary_setting_and_assertiveness', 'Boundary Setting', 'Teaching users how to define, communicate, and enforce personal limits to protect their mental well-being.', 3, 'Scripting & Role-Playing Assertiveness', 'Practice creating boundary scripts, saying ''no,'' and using assertive communication frameworks.', 'You are currently guiding the user through Phase 3 of the ''Boundary Setting'' pathway. Your goal for this phase is: Practice creating boundary scripts and role-play assertive communication.'),
('boundary_setting_and_assertiveness_phase4', 'boundary_setting_and_assertiveness', 'Boundary Setting', 'Teaching users how to define, communicate, and enforce personal limits to protect their mental well-being.', 4, 'Managing Pushback & Guilt', 'Prepare for negative reactions or pushback from others, and manage internal feelings of guilt when enforcing limits.', 'You are currently guiding the user through Phase 4 of the ''Boundary Setting'' pathway. Your goal for this phase is: Prepare the user to manage external pushback and internal feelings of guilt.'),
('life_transition_and_adjustment_phase1', 'life_transition_and_adjustment', 'Life Transition', 'Supporting users through major life changes such as moving, career shifts, graduation, or retirement.', 1, 'Assessing the Impact of Change', 'Explore the specifics of the transition, the loss of the old routine, and the emotional weight of the change.', 'You are currently guiding the user through Phase 1 of the ''Life Transition'' pathway. Your goal for this phase is: Explore the specifics of the transition and the emotional weight of the change.'),
('life_transition_and_adjustment_phase2', 'life_transition_and_adjustment', 'Life Transition', 'Supporting users through major life changes such as moving, career shifts, graduation, or retirement.', 2, 'Normalizing Adjustment Symptoms', 'Validate feelings of disorientation, grief, identity loss, and anxiety associated with navigating the unknown.', 'You are currently guiding the user through Phase 2 of the ''Life Transition'' pathway. Your goal for this phase is: Validate and normalize feelings of disorientation, grief, or identity loss.'),
('life_transition_and_adjustment_phase3', 'life_transition_and_adjustment', 'Life Transition', 'Supporting users through major life changes such as moving, career shifts, graduation, or retirement.', 3, 'Regaining Control & Routine', 'Establish new daily anchors and habits, identifying areas within the user''s control in their new environment.', 'You are currently guiding the user through Phase 3 of the ''Life Transition'' pathway. Your goal for this phase is: Help the user establish new daily anchors and identify areas within their control.'),
('life_transition_and_adjustment_phase4', 'life_transition_and_adjustment', 'Life Transition', 'Supporting users through major life changes such as moving, career shifts, graduation, or retirement.', 4, 'Goal Setting & Future Orientation', 'Build a positive, forward-looking vision and integrate the transition smoothly into the user''s broader life story.', 'You are currently guiding the user through Phase 4 of the ''Life Transition'' pathway. Your goal for this phase is: Build a positive, forward-looking vision and set goals for the new life phase.')
ON CONFLICT (id) DO UPDATE SET dynamic_prompt = EXCLUDED.dynamic_prompt;
