-- Migration: Seed Health Parameter Definitions
-- Auto-generated from raw lab tabular data and wearable parameters

INSERT INTO public.health_parameter_definitions (id, name, category, unit, axis_impact_weights) VALUES
('1751-7', 'Albumin, Serum', 'Albumin', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('6768-6', 'Alkaline Phosphatase, Serum', 'Alkaline phosphatase', 'U/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1968-7', 'Bilirubin Direct, Serum', 'Bilirubin.glucuronidated+Bilirubin.albumin bound', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1975-2', 'Bilirubin Total, Serum', 'Bilirubin', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2324-2', 'GGTP (Gamma GT), Serum', 'Gamma glutamyl transferase', 'U/L', '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2885-2', 'Proteins, Serum', 'Protein', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1920-8', 'SGOT/AST', 'Aspartate aminotransferase', 'U/L', '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1742-6', 'SGPT/ALT', 'Alanine aminotransferase', 'U/L', '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1971-1', 'Bilirubin- Indirect, Serum', 'Bilirubin.non-glucuronidated', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2336-6', 'Globulin', 'Globulin', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1759-0', 'A/G Ratio', 'Albumin/Globulin', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2532-0', 'LDH (Lactate Dehydrogenase)', 'Lactate dehydrogenase', 'U/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('6299-2', 'BUN Urea Nitrogen, Serum', 'Urea nitrogen', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('17861-6', 'Calcium Total, Serum', 'Calcium', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2075-0', 'Chlorides, Serum', 'Chloride', 'mmol/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2160-0', 'Creatinine, Serum', 'Creatinine', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2777-1', 'Phosphorus-Inorganic, Serum', 'Phosphate', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2951-2', 'Sodium, Serum', 'Sodium', 'mmol/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('3091-6', 'Urea, Serum', 'Urea', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('3084-1', 'Uric Acid, Serum', 'Urate', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('44734-2', 'BUN/Creatinine Ratio', 'Urea nitrogen/Creatinine', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('3097-3', 'Urea/Creatinine Ratio', 'Urea nitrogen/Creatinine', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('45066-8', 'EGFR', 'Creatinine & Glomerular filtration rate.predicted panel', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2823-3', 'POTASSIUM', 'Potassium', 'mmol/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('27353-2', 'Estimated average glucose', 'Estimated average glucose', NULL, '{"energy":3,"strength":0,"mind":0,"resilience":1,"heart":1,"hormone":0,"environment":0}'::jsonb),
('41995-2', 'Glycated Hemoglobin (HbA1c)', 'Hemoglobin A1c', NULL, '{"energy":3,"strength":0,"mind":0,"resilience":1,"heart":1,"hormone":0,"environment":0}'::jsonb),
('2339-0', 'Random blood glucose', 'Glucose', NULL, '{"energy":3,"strength":0,"mind":0,"resilience":1,"heart":1,"hormone":0,"environment":0}'::jsonb),
('1557-8', 'Fasting Blood Sugar', 'Glucose^post CFst', NULL, '{"energy":3,"strength":0,"mind":0,"resilience":1,"heart":1,"hormone":0,"environment":0}'::jsonb),
('2513-0', 'Blood Ketone (beta hb)', 'Ketones', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('15069-8', 'Fructosamine', 'Fructosamine', 'mmol/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('27873-9', 'Fasting Insulin', 'Insulin^post CFst', NULL, '{"energy":3,"strength":0,"mind":0,"resilience":1,"heart":1,"hormone":0,"environment":0}'::jsonb),
('14957-5', 'Urinary Microalbumin', 'Albumin', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2756-5', 'pH Urine', 'pH', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2965-2', 'Urine Specific gravity', 'Observation', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('13658-0', 'Urine Urobilinogen', 'Urobilinogen', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5778-6', 'Urine Colour', 'Urine Colour', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5767-9', 'Urine Transparency', 'Urine Transparency', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5794-3', 'Urine Blood - Dip stick', 'Blood', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('53963-5', 'Urine Blood', 'Blood', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('33051-4', 'Urine Red Blood Cells', 'Erythrocytes', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('46702-7', 'Urine Pus cells (Leukocytes)', 'Leukocytes', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('30383-4', 'Urine Epithelial cells', 'Epithelial cells', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5787-7', 'Urine Epithelial cells /hpf', 'Epithelial cells', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('53319-0', 'Urine Crystals', 'Crystals', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('9842-6', 'Urine Cast', 'Casts', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('33218-9', 'Urine Bacteria', 'Bacteria', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5822-2', 'Urine Yeast Cells', 'Yeast', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('32030-9', 'Urine Nitrate', 'Nitrate', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('49779-2', 'URINE KETONE', 'Ketones', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2887-8', 'URINE PROTEIN', 'Protein', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('60026-2', 'Urine Leucocyte Esterase', 'Leukocyte esterase', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1977-8', 'Urine Bile Pigments (Bilirubin)', 'Bilirubin', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('3167-4', 'Volume - Urine  24 hrs', 'Specimen volume', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('19153-6', 'Volume - Urine', 'Specimen volume', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2161-8', 'Urine Creatinine', 'Creatinine', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('9318-7', 'Urine Albumin / Creatinine Ratio', 'Albumin/Creatinine', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('12453-7', 'Urine Amorphous phosphate crystals', 'Phosphate crystals.amorphous', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('12454-5', 'Urine Amorphous urates crystals', 'Urate crystals.amorphous', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1904-2', 'Urine Ascorbic Acid', 'Ascorbate', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('12512-0', 'Urine Calcium  dihydrate crystals', 'Calcium hydrogen phosphate dihydrate crystals', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('33234-6', 'Urine Crystals unidentified', 'Calcium oxalate crystals', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5783-6', 'Urine Calcium oxalate monohydrate crystals', 'Crystals.unidentified', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5775-2', 'Urine Calcium Phosphate', 'Calcium phosphate crystals', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5784-4', 'Urine Cystine crystals', 'Cystine crystals', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5789-3', 'Urine Fatty casts', 'Fatty casts', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('25160-3', 'Urine Granular casts', 'Granular casts', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('25162-9', 'Urine Hyaline casts', 'Hyaline casts', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('30079-8', 'Urine Renal tubular casts', 'Renal tubular casts', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5766-1', 'Urine Ammonium urate crystals', 'Ammonium urate crystals', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('33804-6', 'Urine RBC Casts', 'Erythrocyte casts', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('8247-9', 'Urine Mucus', 'Mucus', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5814-9', 'Urine Triple Phosphate crystals', 'Triple phosphate crystals', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5815-6', 'Urine Tyrosine crystals', 'Tyrosine crystals', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5817-2', 'Urine Uric acid crystals', 'Urate crystals', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5819-8', 'Urine Waxy casts', 'Waxy casts', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('33825-1', 'Urine WBC casts', 'Leukocyte casts', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26444-0', 'Absolute Basophils Count, Blood', 'Basophils', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26449-9', 'Absolute Eosinophil Count, Blood', 'Eosinophils', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26474-7', 'Absolute Lymphocyte Count, Blood', 'Lymphocytes', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26484-6', 'Absolute Monocyte Count, Blood', 'Monocytes', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26499-4', 'Absolute Neutrophil Count, Blood', 'Neutrophils', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('718-7', 'Hemoglobin Hb', 'Hemoglobin', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('4537-7', 'E.S.R. (WESTERGREN)', 'Erythrocyte', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('28539-5', 'MCH', 'Hemoglobin', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('28540-3', 'MCHC', 'Hemoglobin', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('30428-7', 'MCV', 'Observation', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('28542-9', 'MPV Mean Platelet Volume', 'Platelet', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('4544-3', 'PCV Haematocrit', 'Erythrocyte/Blood', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26515-7', 'Platelet Count Thrombocyte count', 'Platelets', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26464-8', 'WBC-Total Counts Leucocytes', 'Leukocytes', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('30385-9', 'RDW (Red Cell Distribution Width) RDW-CV', 'Erythrocyte', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26453-1', 'Red Blood Cells - Blood', 'Erythrocytes', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('51584-1', 'Immature Granulocytes(Ig)', 'Granulocytes.immature', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('69004-0', 'Immature Granulocyte Percentage(Ig%)', 'Granulocytes.immature/Leukocytes', '%', '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26478-8', 'Lymphocyte Percentage', 'Lymphocytes/Leukocytes', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('773-2', 'Nucleated Red Blood Cells %', 'Erythrocytes.nucleated/Erythrocytes', '%', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('30392-5', 'Nucleated Red Blood Cells', 'Erythrocytes.nucleated', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('26505-8', 'SEGMENTED NEUTROPHILS', 'Neutrophils.segmented/Leukocytes', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2093-3', 'Cholesterol-Total, Serum', 'Cholesterol', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('2085-9', 'HDL Cholesterol Direct', 'Cholesterol.in HDL', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('2571-8', 'Triglycerides, Serum', 'Triglyceride', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('43396-1', 'Non - HDL Cholesterol, Serum', 'Cholesterol.non HDL', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('9830-1', 'CHOL/HDL RATIO', 'Cholesterol.total/Cholesterol.in HDL', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('13457-7', 'LDL Cholesterol Cal', 'Cholesterol.in LDL', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('13458-5', 'VLDL Cholesterol Cal', 'Cholesterol.in VLDL', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('11054-4', 'LDL / HDL Cholesterol Ratio Cal', 'Cholesterol.in LDL/Cholesterol.in HDL', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('16616-5', 'HDL / LDL Cholesterol Ratio Cal', 'Cholesterol.in HDL/Cholesterol.in LDL', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('57698-3', 'Ldl Cholesterol - Direct', 'Lipid panel with direct LDL', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('2132-9', 'Vitamin B12 Cyanocobalamin', 'Cobalamins', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1989-3', 'Vitamin D Total-25 Hydroxy', 'Calcidiol', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2236-8', 'Vitamin D2', 'Calciferol', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1990-1', 'Vitamin D3', 'Cholecalciferol', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2923-1', 'Vitamin A', 'Retinol', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2998-3', 'Vitamin B1/thiamin', 'Thiamine', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2924-9', 'Vitamin B2/riboflavin', 'Riboflavin', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('18244-4', 'Vitamin B3/nicotinic Acid', 'Niacin', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2722-7', 'Vitamin B5/pantothenic', 'Pantothenate', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('74442-5', 'Vitamin B6/pyridoxal - 5 - Phosphate', 'Pyridoxal phosphate', 'mmol/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1980-2', 'Vitamin B7/biotin', 'Biotin', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2284-8', 'Vitamin B9/folic Acid', 'Folate', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1823-4', 'Vitamin E', 'Alpha tocopherol', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('81079-6', 'Vitamin K', 'Vitamin K intake', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1874-7', 'APO B : APO A1 RATIO', 'Apolipoprotein B/Apolipoprotein A-I', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('1869-7', 'Apolipoproteins A1, Serum', 'Apolipoprotein A-I', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('1884-6', 'Apolipoproteins B, Serum', 'Apolipoprotein B', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('30522-7', 'High Sensitivity C-reactive Protein (Hs-crp)', 'C reactive protein', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('10835-7', 'Lipoprotein (a) [lp(a)]', 'Lipoprotein (little a)', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('30341-2', 'ESR Automated', 'Erythrocyte', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('14801-5', '% Transferrin Saturation', 'Iron saturation', '%', '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2500-7', 'Total Iron Binding Capacity (Tibc)', 'Iron binding capacity', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2498-4', 'SERUM IRON', 'Iron', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2501-5', 'UIBC, Serum', 'Iron binding capacity.unsaturated', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('20567-4', 'Ferritin', 'Ferritin', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('30567-2', 'Thyroid stimulating immunoglobulins', 'Thyroid stimulating immunoglobulins', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('3021-3', 'Thyroxine binding globulin', 'Thyroxine binding globulin', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('3051-0', 'free t3', 'Triiodothyronine.free', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('3024-7', 'free t4', 'Thyroxine.free', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('3053-6', 'T3, Total Tri Iodothyronine', 'Triiodothyronine', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('3026-2', 'T4, Total Thyroxine', 'Thyroxine', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('3016-3', 'TSH Ultra - Sensitive', 'Thyrotropin', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('15210-8', 'Thyroglobulin Ab', 'Thyroglobulin Ab', NULL, '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('32042-4', 'Thyroperoxidase Ab', 'Thyroperoxidase Ab', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('59740-1', 'Silver', 'Silver', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5574-9', 'Aluminium', 'Aluminum', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5583-0', 'Arsenic', 'Arsenic', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":3}'::jsonb),
('5589-7', 'Barium', 'Barium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('8159-6', 'Beryllium', 'Beryllium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('9493-8', 'Bismuth', 'Bismuth', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5611-9', 'Cadmium', 'Cadmium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":3}'::jsonb),
('5627-5', 'Cobalt', 'Cobalt', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5622-6', 'Chromium', 'Chromium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5616-8', 'Caesium', 'Cesium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5685-3', 'Mercury', 'Mercury', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":3}'::jsonb),
('5683-8', 'Manganese', 'Manganese', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5696-0', 'Molybdenum', 'Molybdenum', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5702-6', 'Nickel', 'Nickel', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5671-3', 'Lead', 'Lead', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":2,"heart":0,"hormone":0,"environment":3}'::jsonb),
('51191-5', 'Antimony', 'Antimony', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5724-0', 'Selenium', 'Selenium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5747-1', 'Tin', 'Tin', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('60172-4', 'Strontium', 'Strontium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5743-0', 'Thallium', 'Thallium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5751-3', 'Uranium', 'Uranium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5756-2', 'Vanadium', 'Vanadium', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5631-7', 'Serum Copper', 'Copper', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5763-8', 'Serum Zinc', 'Zinc', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('33863-2', 'Cystatin C', 'Cystatin C', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('19123-9', 'Magnesium', 'Magnesium', NULL, '{"energy":2,"strength":1,"mind":2,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb),
('53028-7', 'Anti Ccp (Accp)', 'Cyclic citrullinated peptide Ab', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('8061-4', 'Anti Nuclear Antibodies (Ana)', 'Nuclear Ab', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2143-6', 'Cortisol', 'Cortisol', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('1657-6', 'Deoxycortisol', '11-Deoxycortisol', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('2193-1', 'Dehydroepiandrosterone', 'Dehydroepiandrosterone', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2191-5', 'Dhea - Sulphate (Dheas)', 'Dehydroepiandrosterone sulfate', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('2839-9', 'Progesterone', 'Progesterone', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('48795-9', 'FIB-4 INDEX', 'Liver fibrosis score', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1805-1', 'AMYLASE PANCREATIC SERUM', 'Amylase.pancreatic', 'U/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2731-8', 'Parathyroid Hormone (PTH)', 'Parathyrin.intact', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('2357-2', 'Glucose 6 phosphate Dehydrogenase (G6PD )', 'Glucose-6-Phosphate dehydrogenase', 'U/L', '{"energy":3,"strength":0,"mind":0,"resilience":1,"heart":1,"hormone":0,"environment":0}'::jsonb),
('2857-1', 'Prostate Specific Antigen (Male)', 'Prostate specific Ag', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2986-8', 'Testosterone', 'Testosterone', NULL, '{"energy":1,"strength":0,"mind":1,"resilience":0,"heart":0,"hormone":3,"environment":0}'::jsonb),
('11572-5', 'Rheumatoid Factor', 'Rheumatoid factor', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('5195-3', 'HbsAg', 'Hepatitis B virus surface Ag', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('22322-2', 'HbsAb', 'Hepatitis B virus surface Ab', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1988-5', 'CRP', 'C reactive protein', NULL, '{"energy":1,"strength":0,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('16129-9', 'HCV IgG - Clia', 'Hepatitis C virus Ab.IgG', NULL, '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('2572-6', 'Lipase', 'Lipoprotein lipase', 'U/L', '{"energy":0,"strength":2,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('1798-8', 'Amylase', 'Amylase', 'U/L', '{"energy":0,"strength":0,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Step Count', 'Step Count', 'Wearable - activity', 'steps', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Active Calories Burnt', 'Active Calories Burnt', 'Wearable - activity', 'kcal', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Active Minutes', 'Active Minutes', 'Wearable - activity', 'min', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Horizontal Distance Covered', 'Horizontal Distance Covered', 'Wearable - activity', 'km', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Vertical Elevation Gained', 'Vertical Elevation Gained', 'Wearable - activity', 'm', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Total Daily Calories Burned', 'Total Daily Calories Burned', 'Wearable - activity', 'kcal', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Daily Step Goal', 'Daily Step Goal', 'Wearable - activity', 'steps', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Basal Metabolic Rate', 'Basal Metabolic Rate', 'Wearable - activity', 'kcal', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Heart Rate', 'Heart Rate', 'Wearable - vitals', 'bpm', '{"energy":1,"strength":1,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('Resting Heart Rate', 'Resting Heart Rate', 'Wearable - vitals', 'bpm', '{"energy":2,"strength":1,"mind":0,"resilience":2,"heart":3,"hormone":0,"environment":0}'::jsonb),
('Walking Heart Rate', 'Walking Heart Rate', 'Wearable - vitals', 'bpm', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('Heart Rate Recovery', 'Heart Rate Recovery', 'Wearable - vitals', 'bpm', '{"energy":2,"strength":2,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('Blood Pressure Systolic', 'Blood Pressure Systolic', 'Wearable - vitals', 'mmHg', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('Blood Pressure Diastolic', 'Blood Pressure Diastolic', 'Wearable - vitals', 'mmHg', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":3,"hormone":0,"environment":0}'::jsonb),
('Body Temperature', 'Body Temperature', 'Wearable - vitals', '°C', '{"energy":2,"strength":1,"mind":0,"resilience":3,"heart":0,"hormone":0,"environment":0}'::jsonb),
('SPO2 Percentage', 'SPO2 Percentage', 'Wearable - vitals', '%', '{"energy":3,"strength":1,"mind":0,"resilience":1,"heart":2,"hormone":0,"environment":0}'::jsonb),
('Respiratory Rate', 'Respiratory Rate', 'Wearable - vitals', 'breaths/min', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Atrial Fibrillation Burden', 'Atrial Fibrillation Burden', 'Wearable - vitals', '%', '{"energy":2,"strength":1,"mind":0,"resilience":2,"heart":3,"hormone":0,"environment":0}'::jsonb),
('Blood Glucose Record', 'Blood Glucose Record', 'Wearable - vitals', 'mg/dL', '{"energy":3,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Exercise Duration', 'Exercise Duration', 'Wearable - exercise', 'min', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Exercise Calories', 'Exercise Calories', 'Wearable - exercise', 'kcal', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Exercise Length', 'Exercise Length', 'Wearable - exercise', 'km', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Exercise % Time in HR Zone 1', 'Exercise % Time in HR Zone 1', 'Wearable - exercise', '%', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Exercise % Time in HR Zone 2', 'Exercise % Time in HR Zone 2', 'Wearable - exercise', '%', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Exercise % Time in HR Zone 3', 'Exercise % Time in HR Zone 3', 'Wearable - exercise', '%', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Exercise % Time in HR Zone 4', 'Exercise % Time in HR Zone 4', 'Wearable - exercise', '%', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Exercise % Time in HR Zone 5', 'Exercise % Time in HR Zone 5', 'Wearable - exercise', '%', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('VO2 Max', 'VO2 Max', 'Wearable - exercise', 'mL/kg/min', '{"energy":3,"strength":3,"mind":0,"resilience":1,"heart":1,"hormone":0,"environment":0}'::jsonb),
('Sleep Duration', 'Sleep Duration', 'Wearable - sleep', 'hours', '{"energy":2,"strength":1,"mind":3,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Quality', 'Sleep Quality', 'Wearable - sleep', '%', '{"energy":2,"strength":1,"mind":3,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Score', 'Sleep Score', 'Wearable - sleep', 'score', '{"energy":2,"strength":1,"mind":3,"resilience":2,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Average Heart Rate', 'Sleep Average Heart Rate', 'Wearable - sleep', 'bpm', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Average Respiratory Rate', 'Sleep Average Respiratory Rate', 'Wearable - sleep', 'breaths/min', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Skin Temperature Max', 'Sleep Skin Temperature Max', 'Wearable - sleep', '°C', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Skin Temperature Min', 'Sleep Skin Temperature Min', 'Wearable - sleep', '°C', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Average SPO2', 'Sleep Average SPO2', 'Wearable - sleep', '%', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Min SPO2', 'Sleep Min SPO2', 'Wearable - sleep', '%', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Minutes Low Oxygen', 'Sleep Minutes Low Oxygen', 'Wearable - sleep', 'min', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb),
('Sleep Total Snoring Time', 'Sleep Total Snoring Time', 'Wearable - sleep', 'min', '{"energy":2,"strength":1,"mind":0,"resilience":1,"heart":0,"hormone":0,"environment":0}'::jsonb)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    unit = EXCLUDED.unit,
    axis_impact_weights = EXCLUDED.axis_impact_weights;
