-- LibertyMD-owned canonical laboratory parameter dictionary.
-- Portable snapshot: 192 non-patient definitions copied on 2026-08-01.
-- This migration is deliberately self-contained so a future LibertyMD repository
-- does not need Health Twin migrations or tables to recreate its taxonomy.

create table if not exists public.libertymd_health_parameter_definitions (
  id text primary key,
  name text not null unique,
  category text not null default 'Lab Report Parameter'
    check (category = 'Lab Report Parameter'),
  unit text,
  axis_impact_weights jsonb not null default
    '{"energy":0,"strength":0,"mind":0,"resilience":0,"heart":0,"hormone":0,"environment":0}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.libertymd_health_parameter_definitions
  (id, name, category, unit, axis_impact_weights)
values
  ('14801-5', '% Transferrin Saturation', 'Lab Report Parameter', '%', '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('1759-0', 'A/G Ratio', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('26444-0', 'Absolute Basophils Count, Blood', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('26449-9', 'Absolute Eosinophil Count, Blood', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('26474-7', 'Absolute Lymphocyte Count, Blood', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('26484-6', 'Absolute Monocyte Count, Blood', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('26499-4', 'Absolute Neutrophil Count, Blood', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('1751-7', 'Albumin, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('6768-6', 'Alkaline Phosphatase, Serum', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5574-9', 'Aluminium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1798-8', 'Amylase', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1805-1', 'AMYLASE PANCREATIC SERUM', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('53028-7', 'Anti Ccp (Accp)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('8061-4', 'Anti Nuclear Antibodies (Ana)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('51191-5', 'Antimony', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1874-7', 'APO B : APO A1 RATIO', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1869-7', 'Apolipoproteins A1, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1884-6', 'Apolipoproteins B, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5583-0', 'Arsenic', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":2,"environment":3}'::jsonb),
  ('5589-7', 'Barium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('libertymd-cbc-basophils-pct', 'Basophils Percentage', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('8159-6', 'Beryllium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1968-7', 'Bilirubin Direct, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('1975-2', 'Bilirubin Total, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('1971-1', 'Bilirubin- Indirect, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('9493-8', 'Bismuth', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2513-0', 'Blood Ketone (beta hb)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('6299-2', 'BUN Urea Nitrogen, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('44734-2', 'BUN/Creatinine Ratio', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('5611-9', 'Cadmium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":2,"environment":3}'::jsonb),
  ('5616-8', 'Caesium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('17861-6', 'Calcium Total, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('2075-0', 'Chlorides, Serum', 'Lab Report Parameter', 'mmol/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('9830-1', 'CHOL/HDL RATIO', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2093-3', 'Cholesterol-Total, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5622-6', 'Chromium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5627-5', 'Cobalt', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('2143-6', 'Cortisol', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('2160-0', 'Creatinine, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('1988-5', 'CRP', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('custom-metric', 'Custom Metric', 'Lab Report Parameter', 'count', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('33863-2', 'Cystatin C', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2193-1', 'Dehydroepiandrosterone', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1657-6', 'Deoxycortisol', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('2191-5', 'Dhea - Sulphate (Dheas)', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('4537-7', 'E.S.R. (WESTERGREN)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('45066-8', 'EGFR', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('libertymd-cbc-eosinophils-pct', 'Eosinophils Percentage', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('30341-2', 'ESR Automated', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('27353-2', 'Estimated average glucose', 'Lab Report Parameter', null, '{"mind":0,"heart":1,"energy":3,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1557-8', 'Fasting Blood Sugar', 'Lab Report Parameter', null, '{"mind":0,"heart":1,"energy":3,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('27873-9', 'Fasting Insulin', 'Lab Report Parameter', null, '{"mind":0,"heart":1,"energy":3,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('20567-4', 'Ferritin', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('48795-9', 'FIB-4 INDEX', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('3051-0', 'free t3', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('3024-7', 'free t4', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('15069-8', 'Fructosamine', 'Lab Report Parameter', 'mmol/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2324-2', 'GGTP (Gamma GT), Serum', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('2336-6', 'Globulin', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('2357-2', 'Glucose 6 phosphate Dehydrogenase (G6PD )', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":1,"energy":3,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('41995-2', 'Glycated Hemoglobin (HbA1c)', 'Lab Report Parameter', null, '{"mind":0,"heart":1,"energy":3,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('22322-2', 'HbsAb', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5195-3', 'HbsAg', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('16129-9', 'HCV IgG - Clia', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('16616-5', 'HDL / LDL Cholesterol Ratio Cal', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2085-9', 'HDL Cholesterol Direct', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('718-7', 'Hemoglobin Hb', 'Lab Report Parameter', 'g/dL', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('30522-7', 'High Sensitivity C-reactive Protein (Hs-crp)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('69004-0', 'Immature Granulocyte Percentage(Ig%)', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('51584-1', 'Immature Granulocytes(Ig)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2532-0', 'LDH (Lactate Dehydrogenase)', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('11054-4', 'LDL / HDL Cholesterol Ratio Cal', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('57698-3', 'Ldl Cholesterol - Direct', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('13457-7', 'LDL Cholesterol Cal', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5671-3', 'Lead', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":2,"environment":3}'::jsonb),
  ('2572-6', 'Lipase', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('10835-7', 'Lipoprotein (a) [lp(a)]', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('26478-8', 'Lymphocyte Percentage', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('19123-9', 'Magnesium', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('5683-8', 'Manganese', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('28539-5', 'MCH', 'Lab Report Parameter', 'pg', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('28540-3', 'MCHC', 'Lab Report Parameter', 'g/dL', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('30428-7', 'MCV', 'Lab Report Parameter', 'fL', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5685-3', 'Mercury', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":2,"environment":3}'::jsonb),
  ('5696-0', 'Molybdenum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('libertymd-cbc-monocytes-pct', 'Monocytes Percentage', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('28542-9', 'MPV Mean Platelet Volume', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5702-6', 'Nickel', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('43396-1', 'Non - HDL Cholesterol, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('30392-5', 'Nucleated Red Blood Cells', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('773-2', 'Nucleated Red Blood Cells %', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2731-8', 'Parathyroid Hormone (PTH)', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('4544-3', 'PCV Haematocrit', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2756-5', 'pH Urine', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2777-1', 'Phosphorus-Inorganic, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('26515-7', 'Platelet Count Thrombocyte count', 'Lab Report Parameter', 'cells/uL', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2823-3', 'POTASSIUM', 'Lab Report Parameter', 'mmol/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2839-9', 'Progesterone', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('2857-1', 'Prostate Specific Antigen (Male)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2885-2', 'Proteins, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('2339-0', 'Random blood glucose', 'Lab Report Parameter', null, '{"mind":0,"heart":1,"energy":3,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('30385-9', 'RDW (Red Cell Distribution Width) RDW-CV', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('26453-1', 'Red Blood Cells - Blood', 'Lab Report Parameter', '10^6/uL', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('11572-5', 'Rheumatoid Factor', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('26505-8', 'SEGMENTED NEUTROPHILS', 'Lab Report Parameter', '%', '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('5724-0', 'Selenium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5631-7', 'Serum Copper', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2498-4', 'SERUM IRON', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('5763-8', 'Serum Zinc', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1920-8', 'SGOT/AST', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('1742-6', 'SGPT/ALT', 'Lab Report Parameter', 'U/L', '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('59740-1', 'Silver', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2951-2', 'Sodium, Serum', 'Lab Report Parameter', 'mmol/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('60172-4', 'Strontium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('3053-6', 'T3, Total Tri Iodothyronine', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('3026-2', 'T4, Total Thyroxine', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('2986-8', 'Testosterone', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('5743-0', 'Thallium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('15210-8', 'Thyroglobulin Ab', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('30567-2', 'Thyroid stimulating immunoglobulins', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('32042-4', 'Thyroperoxidase Ab', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('3021-3', 'Thyroxine binding globulin', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('5747-1', 'Tin', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2500-7', 'Total Iron Binding Capacity (Tibc)', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('2571-8', 'Triglycerides, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('3016-3', 'TSH Ultra - Sensitive', 'Lab Report Parameter', null, '{"mind":1,"heart":0,"energy":1,"hormone":3,"strength":0,"resilience":0,"environment":0}'::jsonb),
  ('2501-5', 'UIBC, Serum', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('5751-3', 'Uranium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('3091-6', 'Urea, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('3097-3', 'Urea/Creatinine Ratio', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('3084-1', 'Uric Acid, Serum', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('14957-5', 'Urinary Microalbumin', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('9318-7', 'Urine Albumin / Creatinine Ratio', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('5766-1', 'Urine Ammonium urate crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('12453-7', 'Urine Amorphous phosphate crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('12454-5', 'Urine Amorphous urates crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1904-2', 'Urine Ascorbic Acid', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('33218-9', 'Urine Bacteria', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1977-8', 'Urine Bile Pigments (Bilirubin)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('53963-5', 'Urine Blood', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5794-3', 'Urine Blood - Dip stick', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('12512-0', 'Urine Calcium  dihydrate crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('5783-6', 'Urine Calcium oxalate monohydrate crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('5775-2', 'Urine Calcium Phosphate', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('9842-6', 'Urine Cast', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('5778-6', 'Urine Colour', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2161-8', 'Urine Creatinine', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('53319-0', 'Urine Crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('33234-6', 'Urine Crystals unidentified', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('5784-4', 'Urine Cystine crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('30383-4', 'Urine Epithelial cells', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5787-7', 'Urine Epithelial cells /hpf', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5789-3', 'Urine Fatty casts', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('25160-3', 'Urine Granular casts', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('25162-9', 'Urine Hyaline casts', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('49779-2', 'URINE KETONE', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('60026-2', 'Urine Leucocyte Esterase', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('8247-9', 'Urine Mucus', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('32030-9', 'Urine Nitrate', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2887-8', 'URINE PROTEIN', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('46702-7', 'Urine Pus cells (Leukocytes)', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('33804-6', 'Urine RBC Casts', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('33051-4', 'Urine Red Blood Cells', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('30079-8', 'Urine Renal tubular casts', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('2965-2', 'Urine Specific gravity', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5767-9', 'Urine Transparency', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5814-9', 'Urine Triple Phosphate crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5815-6', 'Urine Tyrosine crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5817-2', 'Urine Uric acid crystals', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":2,"resilience":1,"environment":0}'::jsonb),
  ('13658-0', 'Urine Urobilinogen', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('5819-8', 'Urine Waxy casts', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('33825-1', 'Urine WBC casts', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('5822-2', 'Urine Yeast Cells', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb),
  ('5756-2', 'Vanadium', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2923-1', 'Vitamin A', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2998-3', 'Vitamin B1/thiamin', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2132-9', 'Vitamin B12 Cyanocobalamin', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('2924-9', 'Vitamin B2/riboflavin', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('18244-4', 'Vitamin B3/nicotinic Acid', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2722-7', 'Vitamin B5/pantothenic', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('74442-5', 'Vitamin B6/pyridoxal - 5 - Phosphate', 'Lab Report Parameter', 'mmol/L', '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('1980-2', 'Vitamin B7/biotin', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('2284-8', 'Vitamin B9/folic Acid', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('1989-3', 'Vitamin D Total-25 Hydroxy', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('2236-8', 'Vitamin D2', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('1990-1', 'Vitamin D3', 'Lab Report Parameter', null, '{"mind":2,"heart":0,"energy":2,"hormone":0,"strength":1,"resilience":0,"environment":0}'::jsonb),
  ('1823-4', 'Vitamin E', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('81079-6', 'Vitamin K', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('13458-5', 'VLDL Cholesterol Cal', 'Lab Report Parameter', null, '{"mind":0,"heart":3,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('19153-6', 'Volume - Urine', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('3167-4', 'Volume - Urine  24 hrs', 'Lab Report Parameter', null, '{"mind":0,"heart":0,"energy":0,"hormone":0,"strength":0,"resilience":1,"environment":0}'::jsonb),
  ('26464-8', 'WBC-Total Counts Leucocytes', 'Lab Report Parameter', 'cells/uL', '{"mind":0,"heart":0,"energy":1,"hormone":0,"strength":0,"resilience":3,"environment":0}'::jsonb)
on conflict (id) do update
set name = excluded.name,
    category = excluded.category,
    unit = excluded.unit,
    axis_impact_weights = excluded.axis_impact_weights,
    updated_at = now();

alter table public.libertymd_lab_results
  drop constraint if exists libertymd_lab_results_parameter_id_fkey;

alter table public.libertymd_lab_results
  drop constraint if exists libertymd_lab_results_libertymd_parameter_fkey;

alter table public.libertymd_lab_results
  add constraint libertymd_lab_results_libertymd_parameter_fkey
  foreign key (parameter_id)
  references public.libertymd_health_parameter_definitions(id);

alter table public.libertymd_health_parameter_definitions enable row level security;

revoke all on table public.libertymd_health_parameter_definitions
  from public, anon, authenticated;
grant select, insert, update, delete
  on table public.libertymd_health_parameter_definitions
  to service_role;

comment on table public.libertymd_health_parameter_definitions is
  'LibertyMD-owned canonical lab dictionary. Independent of Health Twin and portable during repository hive-off.';
comment on column public.libertymd_lab_results.parameter_id is
  'Canonical LibertyMD parameter id referencing libertymd_health_parameter_definitions.';
